// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1784528226);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1784528226);
user_pref("app.update.lastUpdateTime.glean-addons-daily", 1784528226);
user_pref("app.update.lastUpdateTime.region-update-timer", 1784528226);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1784528226);
user_pref("app.update.lastUpdateTime.telemetry_untrustedmodules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1784528226);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 172);
user_pref("browser.newtabpage.activity-stream.impressionId", "{327ca475-a70a-4f61-bd6d-26ffd0894dd1}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "never");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\",\"webcompat@mozilla.org\",\"screenshots@mozilla.org\",\"pictureinpicture@mozilla.org\",\"formautofill@mozilla.org\"]");
user_pref("browser.privacySegmentation.createdShortcut", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.lastColdStartupCheck", 1784528197);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"reset-pbm-toolbar-button\",\"unified-extensions-button\",\"new-tab-button\",\"alltabs-button\",\"personal-bookmarks\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\"],\"vertical-tabs\":[],\"PersonalToolbar\":[]},\"seen\":[\"reset-pbm-toolbar-button\",\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"TabsToolbar\",\"vertical-tabs\",\"PersonalToolbar\"],\"currentVersion\":24,\"newElementCount\":2}");
user_pref("captchadetection.lastSubmission", 1784528);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "b0bacafe-b0ba-cafe-b0ba-cafeb0bacafe");
user_pref("datareporting.dau.cachedUsageProfileID", "beefbeef-beef-beef-beef-beeefbeefbee");
user_pref("datareporting.policy.firstRunURL", "https://www.mozilla.org/privacy/firefox/");
user_pref("distribution.iniFile.exists.appversion", "152.0.4-beta.27");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.filesystem.pathcheck.disabled", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.lastAppBuildId", "20260716211915");
user_pref("extensions.lastAppVersion", "152.0.4-beta.27");
user_pref("extensions.lastPlatformVersion", "152.0.4");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"b7ff16a9-16a9-4bf5-9bcf-1d7665b765fa\",\"formautofill@mozilla.org\":\"0850bb83-7f4a-4550-a8a3-23bbd60bb2f7\",\"ipp-activator@mozilla.com\":\"5d781de7-57af-4e77-800a-f02e4651a8dc\",\"pictureinpicture@mozilla.org\":\"ce86a9c5-ed49-4bd2-b5db-261a63f79223\",\"addons-search-detection@mozilla.com\":\"665eb043-904e-4eac-b7b0-2705d381b921\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"7c118d31-5e1b-499f-ac54-9d8f96ece4c2\",\"firefox-compact-dark@mozilla.org\":\"fe29d4ac-e0f7-4f6f-b04d-3a95228ccc43\",\"uBlock0@raymondhill.net\":\"c51b09a3-1243-484d-959f-c314efbdf1de\"}");
user_pref("font.system.whitelist", "Arial,Calibri,Cambria Math,Consolas,Courier New,Georgia,Nirmala UI,Segoe UI,Tahoma,Times New Roman,Trebuchet MS,Verdana,Lucida Console,맑은 고딕 Semilight,Nirmala UI Semilight,Ebrima,微软雅黑 Light,Palatino Linotype,Yu Gothic UI Semibold,Microsoft JhengHei Light,Segoe UI Variable,MS UI Gothic,Symbol,MS Gothic,Microsoft Yi Baiti,Constantia,Lucida Sans Unicode,Yu Gothic UI Semilight,Malgun Gothic,新宋体,Microsoft Sans Serif,Segoe UI Semilight,Yu Gothic,Twemoji Mozilla,Mongolian Baiti,新細明體-ExtB,微軟正黑體 Light,Segoe Script,Microsoft Himalaya,PMingLiU-ExtB,Sitka,Calibri Light,MV Boli,Microsoft JhengHei");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.getdisplaymedia.screencapturekit.enabled", false);
user_pref("media.getdisplaymedia.screencapturekit.picker.enabled", false);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.profileId", "369c7c4d-98a6-4106-ba8c-b9e0172b8afd");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("sanity-test.device-id", "0x15e7");
user_pref("sanity-test.driver-version", "31.0.21924.4004");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20260716211915");
user_pref("security.sandbox.warn_unprivileged_namespaces", false);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"bookmarksExpandedFolders\":[],\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("toolkit.profiles.newProfileSubmitted", true);
user_pref("toolkit.profiles.storeID", "e900f7f6");
user_pref("toolkit.startup.last_success", 1784528192);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.cachedProfileGroupID", "decafdec-afde-cafd-ecaf-decafdecafde");
user_pref("toolkit.telemetry.previousBuildID", "20260716211915");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("webgl.force-enabled", true);
