# Generated by Django 5.0.6 on 2026-09-08 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0007_crm_visit_alerts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyprospect',
            name='address',
            field=models.CharField(blank=True, help_text='Ej: Mz. D Lote 12, Urb. La Encalada', max_length=300, verbose_name='Dirección (Mz/Lote/Calle)'),
        ),
        migrations.AlterField(
            model_name='propertyprospect',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to=settings.AUTH_USER_MODEL, verbose_name='Agente'),
        ),
        migrations.AlterField(
            model_name='propertyprospect',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Área m²'),
        ),
        migrations.AlterField(
            model_name='propertyprospect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='propertyprospect',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('PEN', 'PEN (Soles)')], default='USD', max_length=5, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='propertyprospect',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='propertyprospect',
            table=None,
        ),
    ]
