# Generated by Django 5.2.10 on 2026-02-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propifai', '0001_initial'),
        ('requerimientos', '0004_add_fuente_red_inmobiliaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_total', models.DecimalField(decimal_places=2, help_text='Puntuación total de compatibilidad', max_digits=5, verbose_name='Score total (0-100)')),
                ('score_detalle', models.JSONField(help_text='Diccionario JSON con el aporte individual de cada campo', verbose_name='Detalle del score')),
                ('fase_eliminada', models.CharField(blank=True, help_text='Nombre del campo discriminatorio por el que fue eliminada (si aplica)', max_length=50, null=True, verbose_name='Fase eliminada')),
                ('porcentaje_compatibilidad', models.DecimalField(decimal_places=2, help_text='Representación visual del score (0-100)', max_digits=5, verbose_name='Porcentaje de compatibilidad')),
                ('ejecutado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de ejecución')),
                ('notificado_al_agente', models.BooleanField(default=False, help_text='Indica si los resultados fueron notificados al agente responsable', verbose_name='Notificado al agente')),
                ('notificado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de notificación')),
                ('ranking', models.PositiveIntegerField(blank=True, help_text='Posición que ocupó esta propiedad en el matching específico', null=True, verbose_name='Ranking en el matching')),
                ('propiedad', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='propifai.propifaiproperty', verbose_name='Propiedad evaluada')),
                ('requerimiento', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='requerimientos.requerimiento', verbose_name='Requerimiento evaluado')),
            ],
            options={
                'verbose_name': 'Resultado de Matching',
                'verbose_name_plural': 'Resultados de Matching',
                'db_table': 'matching_matchresult',
                'ordering': ['-ejecutado_en', '-score_total'],
                'indexes': [models.Index(fields=['requerimiento', 'score_total'], name='matching_ma_requeri_34e946_idx'), models.Index(fields=['ejecutado_en'], name='matching_ma_ejecuta_52cb4e_idx'), models.Index(fields=['notificado_al_agente'], name='matching_ma_notific_808621_idx')],
                'unique_together': {('requerimiento', 'propiedad', 'ejecutado_en')},
            },
        ),
    ]
