// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1784528049);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1784543859);
user_pref("app.update.lastUpdateTime.glean-addons-daily", 1784528049);
user_pref("app.update.lastUpdateTime.region-update-timer", 1784528049);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1784528049);
user_pref("app.update.lastUpdateTime.telemetry_untrustedmodules_ping", 1784536513);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1784528049);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 172);
user_pref("browser.newtabpage.activity-stream.impressionId", "{c41bcfa2-06b3-475b-ad51-0e6bb8cf0526}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "never");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\",\"webcompat@mozilla.org\",\"screenshots@mozilla.org\",\"pictureinpicture@mozilla.org\",\"formautofill@mozilla.org\"]");
user_pref("browser.privacySegmentation.createdShortcut", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.lastColdStartupCheck", 1784528021);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"reset-pbm-toolbar-button\",\"unified-extensions-button\",\"new-tab-button\",\"alltabs-button\",\"personal-bookmarks\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\"],\"vertical-tabs\":[],\"PersonalToolbar\":[]},\"seen\":[\"reset-pbm-toolbar-button\",\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"TabsToolbar\",\"vertical-tabs\",\"PersonalToolbar\"],\"currentVersion\":24,\"newElementCount\":2}");
user_pref("captchadetection.lastSubmission", 1784528);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "b0bacafe-b0ba-cafe-b0ba-cafeb0bacafe");
user_pref("datareporting.dau.cachedUsageProfileID", "beefbeef-beef-beef-beef-beeefbeefbee");
user_pref("datareporting.policy.firstRunURL", "https://www.mozilla.org/privacy/firefox/");
user_pref("distribution.iniFile.exists.appversion", "152.0.4-beta.27");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.filesystem.pathcheck.disabled", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.lastAppBuildId", "20260716211915");
user_pref("extensions.lastAppVersion", "152.0.4-beta.27");
user_pref("extensions.lastPlatformVersion", "152.0.4");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"5d6e6d0d-4f67-400d-aa51-607292e06f47\",\"formautofill@mozilla.org\":\"e2b96030-426c-40d4-9f30-0c5a41a323f0\",\"ipp-activator@mozilla.com\":\"6a7452d4-1183-4006-9ca4-e37e66abf4e9\",\"pictureinpicture@mozilla.org\":\"efe0abba-c998-4ec1-b140-5dff2c9fe88d\",\"addons-search-detection@mozilla.com\":\"29d4f3e7-7a74-490b-97ed-c038553636b7\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"91f951dd-abda-4364-9168-95320f3022bd\",\"firefox-compact-dark@mozilla.org\":\"252f8a86-6df8-45c3-b52f-dfe9b8e1d31a\",\"uBlock0@raymondhill.net\":\"94a4a774-879b-4584-baac-9cfd8e0e7dc5\"}");
user_pref("font.system.whitelist", "Arial,Calibri,Cambria Math,Consolas,Courier New,Georgia,Nirmala UI,Segoe UI,Tahoma,Times New Roman,Trebuchet MS,Verdana,Palatino Linotype,Myanmar Text,Yu Gothic UI,Yu Gothic UI Semilight,Mongolian Baiti,MS PGothic,Microsoft Yi Baiti,ＭＳ ゴシック,MV Boli,Segoe UI Historic,SimSun-ExtB,Yu Gothic Medium,Webdings,Wingdings,游ゴシック Light,Microsoft Tai Le,Sylfaen,Gadugi,Sitka Text,Microsoft JhengHei Light,微软雅黑,MingLiU_HKSCS-ExtB,Microsoft PhagsPa,微软雅黑 Light,游ゴシック,맑은 고딕,MS UI Gothic,Ebrima,Segoe UI Black,Segoe UI Semilight");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1784528732);
user_pref("media.getdisplaymedia.screencapturekit.enabled", false);
user_pref("media.getdisplaymedia.screencapturekit.picker.enabled", false);
user_pref("media.gmp-manager.buildID", "20260716211915");
user_pref("media.gmp-manager.lastCheck", 1784528358);
user_pref("media.gmp-manager.lastEmptyCheck", 1784528358);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.profileId", "1e65c535-0056-47b5-9d50-faa974f6a688");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1784528732);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1784528732246");
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("sanity-test.device-id", "0x15e7");
user_pref("sanity-test.driver-version", "31.0.21924.4004");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20260716211915");
user_pref("security.sandbox.warn_unprivileged_namespaces", false);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"bookmarksExpandedFolders\":[],\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1784528732);
user_pref("toolkit.profiles.newProfileSubmitted", true);
user_pref("toolkit.profiles.storeID", "ad4484d0");
user_pref("toolkit.startup.last_success", 1784528011);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.cachedProfileGroupID", "decafdec-afde-cafd-ecaf-decafdecafde");
user_pref("toolkit.telemetry.previousBuildID", "20260716211915");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("webgl.force-enabled", true);
