# Generated by Django 5.0.6 on 2026-09-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('n8n_bridge', '0005_propertybotconfiguration_captacion_delay'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='propertybotinitialresponse',
            new_name='n8n_propert_receive_3fbb0a_idx',
            old_name='n8n_propert_receive_07fc15_idx',
        ),
        migrations.RenameIndex(
            model_name='propertybotinitialresponse',
            new_name='n8n_propert_reason__92da5e_idx',
            old_name='n8n_propert_reason__4fa0c4_idx',
        ),
    ]
