# Generated by Django 5.0.6 on 2026-02-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captura', '0001_initial'),
        ('semillas', '0004_alter_fuenteweb_id'),
    ]

    operations = [
        # Eliminar índices con campos de orden descendente solo del estado de Django
        # (no de la base de datos, porque pueden no existir debido a bug de MSSQL)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='capturacruda',
                    name='captura_cap_fuente__5bddf3_idx',
                ),
                migrations.RemoveIndex(
                    model_name='eventodeteccion',
                    name='captura_eve_fuente__e6ec8b_idx',
                ),
                migrations.RemoveIndex(
                    model_name='capturacruda',
                    name='captura_cap_estado_06fd85_idx',
                ),
            ],
            database_operations=[],
        ),
        migrations.RemoveField(
            model_name='capturacruda',
            name='estado',
        ),
        migrations.AddField(
            model_name='capturacruda',
            name='azure_blob_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del blob en Azure Storage'),
        ),
        migrations.AddField(
            model_name='capturacruda',
            name='azure_blob_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL del blob en Azure Storage'),
        ),
        migrations.AddField(
            model_name='capturacruda',
            name='contenido_binario_blob',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del blob con contenido binario'),
        ),
        migrations.AddField(
            model_name='capturacruda',
            name='estado_http',
            field=models.CharField(default='exito', max_length=15, verbose_name='Estado HTTP de la descarga'),
        ),
        migrations.AddField(
            model_name='capturacruda',
            name='estado_procesamiento',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('texto_extraido_ok', 'Texto Extraído OK'), ('requiere_ocr', 'Requiere OCR'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado de procesamiento'),
        ),
        migrations.AddField(
            model_name='capturacruda',
            name='metadata_tecnica',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadatos técnicos (headers, etc.)'),
        ),
        migrations.AddField(
            model_name='capturacruda',
            name='pdf_num_paginas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de páginas (PDFs)'),
        ),
        migrations.AddField(
            model_name='capturacruda',
            name='pdf_tiene_texto',
            field=models.BooleanField(blank=True, null=True, verbose_name='PDF tiene texto seleccionable'),
        ),
        migrations.AddField(
            model_name='capturacruda',
            name='texto_extraido',
            field=models.TextField(blank=True, null=True, verbose_name='Texto extraído del documento'),
        ),
        migrations.AddField(
            model_name='capturacruda',
            name='tipo_documento',
            field=models.CharField(choices=[('html', 'HTML'), ('pdf_nativo', 'PDF Nativo'), ('pdf_escaneado', 'PDF Escaneado'), ('json', 'JSON'), ('xml', 'XML'), ('otro', 'Otro')], default='html', max_length=20, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='capturacruda',
            name='contenido_html',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido HTML/texto crudo'),
        ),
        migrations.AlterField(
            model_name='capturacruda',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventodeteccion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='capturacruda',
            index=models.Index(fields=['fuente', 'fecha_captura'], name='captura_cap_fuente__5c7bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='capturacruda',
            index=models.Index(fields=['estado_procesamiento', 'fecha_captura'], name='captura_cap_estado__447d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='capturacruda',
            index=models.Index(fields=['tipo_documento'], name='captura_cap_tipo_do_1ed227_idx'),
        ),
    ]
