# Generated by Django 5.2.10 on 2026-02-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturacruda',
            name='azure_blob_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del blob en Azure Storage'),
        ),
        migrations.AddField(
            model_name='capturacruda',
            name='azure_blob_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL del blob en Azure Storage'),
        ),
        migrations.AlterField(
            model_name='capturacruda',
            name='contenido_html',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido HTML crudo'),
        ),
    ]
