# Generated by Django 5.2.10 on 2026-02-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captura', '0002_capturacruda_azure_blob_name_and_more'),
        ('semillas', '0002_fuenteweb_categoria'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='capturacruda',
            name='captura_cap_fuente__5bddf3_idx',
        ),
        migrations.AddIndex(
            model_name='capturacruda',
            index=models.Index(fields=['fuente', 'fecha_captura'], name='captura_cap_fuente__5c7bf8_idx'),
        ),
    ]
