# Generated by Django 5.0.6 on 2026-02-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captura', '0002_initial_consolidada'),
        ('semillas', '0004_alter_fuenteweb_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventodeteccion',
            index=models.Index(fields=['fuente', '-fecha_deteccion'], name='captura_eve_fuente__e6ec8b_idx'),
        ),
    ]
