# Oryx manifest file to help with framework detection
[python]
version = "3.12"
framework = "django"
framework_version = "5.2.8"

[build]
build_command = "pip install -r requirements.txt"
run_command = "export PYTHONPATH=$(pwd):$(pwd)/webapp && python webapp/manage.py collectstatic --noinput && gunicorn --bind=0.0.0.0 --timeout 600 --access-logfile '-' --error-logfile '-' webapp.wsgi:application"