# Generated by Django 5.2.10 on 2026-05-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0005_add_extractor_log_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento',
            name='verificado',
            field=models.BooleanField(default=False, help_text='Marcar como TRUE cuando el requerimiento haya sido revisado manualmente', verbose_name='Verificado'),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='fuente',
            field=models.CharField(db_index=True, default='otro', help_text='Grupo de WhatsApp de donde proviene el mensaje (nombre real del grupo)', max_length=60, verbose_name='Grupo WhatsApp'),
        ),
    ]
