# Generated by Django 5.2.10 on 2026-04-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_intelligencecollection_intelligencedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligencecollection',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción de la colección y su propósito', verbose_name='Descripción'),
        ),
        # Constraints removidas por compatibilidad con Django 5.0.6
        # Las constraints con condition no son compatibles en esta versión
    ]
