# Generated by Django 5.2.10 on 2026-04-23 21:47

from django.db import migrations, models


def assign_usernames(apps, schema_editor):
    """Asigna usernames únicos a usuarios existentes que no tienen username."""
    User = apps.get_model('intelligence', 'User')
    for user in User.objects.all():
        if not user.username:
            # Usar email, phone o un default basado en el id
            if user.email:
                base = user.email.split('@')[0]
            elif user.phone:
                base = f'user_{user.phone[-8:]}'
            else:
                base = f'user_{str(user.id)[:8]}'
            
            # Asegurar unicidad
            username = base
            counter = 1
            while User.objects.filter(username=username).exists():
                username = f'{base}_{counter}'
                counter += 1
            user.username = username
            user.save(update_fields=['username'])


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0008_episodicmemory_only'),
    ]

    operations = [
        # 1. Agregar campos sin unique constraint primero
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último login'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Contraseña'),
        ),
        # 2. Agregar username SIN unique aún
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre de usuario'),
        ),
        # 3. Asignar usernames únicos a registros existentes
        migrations.RunPython(assign_usernames, reverse_code=migrations.RunPython.noop),
        # 4. Ahora sí crear el unique constraint
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario'),
        ),
        # 5. Índice
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='intelligenc_usernam_de90aa_idx'),
        ),
    ]
