"""
Generated by Django 5.0.6 on 2026-05-03

Migración v2 del sistema de niveles de inteligencia:

1. Renombra Role.allowed_levels → default_level + max_level + default_domains
2. Renombra IntelligenceCollection.access_level → min_level + domain + is_public
3. Crea modelo UserIntelligenceProfile
4. Data migration: migra datos existentes de allowed_levels a default_level/max_level
5. Data migration: migra access_level a min_level, asigna domain='general' por defecto
6. Data migration: crea UserIntelligenceProfile para usuarios existentes

CORREGIDO: Las data migrations ahora se ejecutan ANTES de RemoveField,
para que los campos viejos aún existan cuando se leen.
"""

from django.db import migrations, models
import django.db.models.deletion
import uuid


def migrate_role_allowed_levels(apps, schema_editor):
    """
    Migra Role.allowed_levels (JSON list) → default_level + max_level.
    - Si allowed_levels = [1, 2, 3] → default_level=1, max_level=3
    - Si allowed_levels = [] o None → default_level=1, max_level=1
    - Si allowed_levels = [5] → default_level=5, max_level=5
    """
    Role = apps.get_model('intelligence', 'Role')
    for role in Role.objects.all():
        levels = role.allowed_levels or []
        if not isinstance(levels, list):
            levels = []
        # Filtrar solo valores enteros válidos 1-5
        valid_levels = [l for l in levels if isinstance(l, int) and 1 <= l <= 5]
        if valid_levels:
            role.default_level = min(valid_levels)
            role.max_level = max(valid_levels)
        else:
            role.default_level = 1
            role.max_level = 1
        # default_domains: heredar de capabilities si existe, sino ['general']
        caps = role.capabilities or {}
        if isinstance(caps, dict) and 'domains' in caps:
            role.default_domains = caps['domains']
        else:
            role.default_domains = ['general']
        role.save()


def reverse_migrate_role_allowed_levels(apps, schema_editor):
    """
    Reversa: reconstruye allowed_levels desde default_level y max_level.
    """
    Role = apps.get_model('intelligence', 'Role')
    for role in Role.objects.all():
        role.allowed_levels = list(range(role.default_level, role.max_level + 1))
        role.save()


def migrate_collection_access_level(apps, schema_editor):
    """
    Migra IntelligenceCollection.access_level → min_level.
    Asigna domain='general' y is_public=False por defecto.
    """
    IntelligenceCollection = apps.get_model('intelligence', 'IntelligenceCollection')
    for coll in IntelligenceCollection.objects.all():
        coll.min_level = coll.access_level if coll.access_level else 1
        coll.domain = 'general'
        coll.is_public = False
        coll.save()


def reverse_migrate_collection_access_level(apps, schema_editor):
    """
    Reversa: reconstruye access_level desde min_level.
    """
    IntelligenceCollection = apps.get_model('intelligence', 'IntelligenceCollection')
    for coll in IntelligenceCollection.objects.all():
        coll.access_level = coll.min_level
        coll.save()


def create_profiles_for_existing_users(apps, schema_editor):
    """
    Crea UserIntelligenceProfile para todos los usuarios existentes.
    Hereda level del rol del usuario y allowed_domains del rol.
    """
    User = apps.get_model('intelligence', 'User')
    UserIntelligenceProfile = apps.get_model('intelligence', 'UserIntelligenceProfile')
    
    for user in User.objects.all():
        if hasattr(user, 'intelligence_profile'):
            continue  # Ya tiene perfil
        
        level = 1
        allowed_domains = ['general']
        
        if user.role:
            level = user.role.default_level or 1
            allowed_domains = user.role.default_domains or ['general']
        
        UserIntelligenceProfile.objects.create(
            user=user,
            level=level,
            allowed_domains=allowed_domains,
        )


def reverse_create_profiles(apps, schema_editor):
    """
    Reversa: elimina todos los perfiles creados.
    """
    UserIntelligenceProfile = apps.get_model('intelligence', 'UserIntelligenceProfile')
    UserIntelligenceProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0013_add_table_relationships'),
    ]

    operations = [
        # ═══════════════════════════════════════════════════════════════════
        # Paso 1: Renombrar Role.allowed_levels → default_level + max_level
        # ═══════════════════════════════════════════════════════════════════
        # 1a. Crear campos NUEVOS primero (allowed_levels aún existe)
        migrations.AddField(
            model_name='role',
            name='default_level',
            field=models.IntegerField(choices=[(1, 'Nivel 1 - Consulta básica'), (2, 'Nivel 2 - Consulta avanzada'), (3, 'Nivel 3 - Análisis'), (4, 'Nivel 4 - Edición'), (5, 'Nivel 5 - Administración total')], default=1, help_text='Nivel base que reciben los usuarios de este rol (1-5)', verbose_name='Nivel por defecto'),
        ),
        migrations.AddField(
            model_name='role',
            name='max_level',
            field=models.IntegerField(choices=[(1, 'Nivel 1 - Consulta básica'), (2, 'Nivel 2 - Consulta avanzada'), (3, 'Nivel 3 - Análisis'), (4, 'Nivel 4 - Edición'), (5, 'Nivel 5 - Administración total')], default=5, help_text='Nivel máximo que puede alcanzar un usuario de este rol (1-5)', verbose_name='Nivel máximo'),
        ),
        migrations.AddField(
            model_name='role',
            name='default_domains',
            field=models.JSONField(default=list, help_text="Lista de dominios asignados por defecto a usuarios de este rol (ej: ['publico', 'legal'])", verbose_name='Dominios por defecto'),
        ),

        # 1b. Data migration: migrar datos de allowed_levels → default_level + max_level
        #     EJECUTADA AQUÍ: allowed_levels AÚN EXISTE en la BD
        migrations.RunPython(
            migrate_role_allowed_levels,
            reverse_migrate_role_allowed_levels,
        ),

        # 1c. AHORA eliminar el campo viejo allowed_levels
        migrations.RemoveField(
            model_name='role',
            name='allowed_levels',
        ),

        # ═══════════════════════════════════════════════════════════════════
        # Paso 2: Renombrar IntelligenceCollection.access_level → min_level
        # ═══════════════════════════════════════════════════════════════════
        # 2a. Crear campos NUEVOS primero (access_level aún existe)
        migrations.AddField(
            model_name='intelligencecollection',
            name='min_level',
            field=models.IntegerField(choices=[(1, 'Nivel 1 - Consulta básica'), (2, 'Nivel 2 - Consulta avanzada'), (3, 'Nivel 3 - Análisis'), (4, 'Nivel 4 - Edición'), (5, 'Nivel 5 - Administración total')], default=1, help_text='Nivel mínimo que debe tener el usuario para acceder a esta colección (1-5)', verbose_name='Nivel mínimo requerido'),
        ),
        migrations.AddField(
            model_name='intelligencecollection',
            name='domain',
            field=models.CharField(choices=[('publico', 'Público'), ('legal', 'Legal / Regulatorio'), ('marketing', 'Marketing / Ventas'), ('escuela', 'Escuela / Capacitación'), ('gerencia', 'Gerencia / Estrategia'), ('ti', 'TI / Infraestructura'), ('general', 'General / Sin clasificar')], default='general', help_text='Dominio al que pertenece esta colección. Controla qué usuarios pueden verla según sus dominios asignados.', max_length=50, verbose_name='Dominio funcional'),
        ),
        migrations.AddField(
            model_name='intelligencecollection',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Si es True, cualquier usuario autenticado puede verla (sin importar dominio). Si es False, solo usuarios con el dominio asignado.', verbose_name='Colección pública'),
        ),

        # 2b. Data migration: migrar access_level → min_level
        #     EJECUTADA AQUÍ: access_level AÚN EXISTE en la BD
        migrations.RunPython(
            migrate_collection_access_level,
            reverse_migrate_collection_access_level,
        ),

        # 2c. AHORA eliminar el campo viejo access_level
        migrations.RemoveField(
            model_name='intelligencecollection',
            name='access_level',
        ),

        # ═══════════════════════════════════════════════════════════════════
        # Paso 3: Crear modelo UserIntelligenceProfile
        # ═══════════════════════════════════════════════════════════════════
        migrations.CreateModel(
            name='UserIntelligenceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(choices=[(1, 'Nivel 1 - Consulta básica'), (2, 'Nivel 2 - Consulta avanzada'), (3, 'Nivel 3 - Análisis'), (4, 'Nivel 4 - Edición'), (5, 'Nivel 5 - Administración total')], default=1, help_text='Nivel real del usuario (1-5). Se hereda del rol al crear, pero puede ajustarse individualmente.', verbose_name='Nivel del usuario')),
                ('allowed_domains', models.JSONField(default=list, help_text="Lista de dominios a los que el usuario tiene acceso (ej: ['publico', 'legal', 'marketing'])", verbose_name='Dominios permitidos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_collections', models.ManyToManyField(blank=True, related_name='blocked_profiles', to='intelligence.intelligencecollection', verbose_name='Colecciones bloqueadas')),
                ('extra_collections', models.ManyToManyField(blank=True, related_name='extra_profiles', to='intelligence.intelligencecollection', verbose_name='Colecciones extra')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_profile', to='intelligence.user', verbose_name='Usuario')),
            ],
            options={
                'db_table': 'intelligence_user_profiles',
                'verbose_name': 'Perfil de Inteligencia',
                'verbose_name_plural': 'Perfiles de Inteligencia',
            },
        ),
        migrations.AddIndex(
            model_name='userintelligenceprofile',
            index=models.Index(fields=['user', 'level'], name='intelligenc_user_id_8a6b7c_idx'),
        ),

        # ═══════════════════════════════════════════════════════════════════
        # Paso 4: Crear perfiles para usuarios existentes
        # ═══════════════════════════════════════════════════════════════════
        migrations.RunPython(
            create_profiles_for_existing_users,
            reverse_create_profiles,
        ),
    ]
