# Generated by Django 5.0.6 on 2026-09-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_intelligence', '0011_durablejob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrunstep',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
