# Generated by Django 5.0.6 on 2026-01-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semillas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuenteweb',
            name='categoria',
            field=models.CharField(choices=[('oferta', 'Oferta Activa (Portales)'), ('legal', 'Normativa y Leyes'), ('infraestructura', 'Obras Públicas'), ('inteligencia', 'Análisis de Mercado'), ('riesgo', 'Contexto Socio-Ambiental'), ('actores', 'Constructoras y Agentes')], default='oferta', max_length=20, verbose_name='Categoría de inteligencia'),
        ),
    ]
