# Generated by Django 5.2.10 on 2026-02-03 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semillas', '0002_fuenteweb_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuenteweb',
            name='es_semilla_activa',
            field=models.BooleanField(default=True, verbose_name='Es semilla activa (genera hijos)'),
        ),
        migrations.AlterField(
            model_name='fuenteweb',
            name='descubierta_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuentes_descubiertas', to='semillas.fuenteweb', verbose_name='Descubierta por (fuente padre)'),
        ),
        migrations.AlterField(
            model_name='fuenteweb',
            name='tipo',
            field=models.CharField(choices=[('semilla_listado', 'Semilla Listado'), ('documento_directo_html', 'Documento Directo HTML'), ('documento_directo_pdf', 'Documento Directo PDF'), ('api_feed', 'API/Feed')], default='semilla_listado', max_length=30, verbose_name='Tipo de fuente'),
        ),
    ]
