# Generated by Django 5.0.6 on 2026-01-30 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semillas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturaCruda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_captura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de captura')),
                ('estado', models.CharField(choices=[('exito', 'Éxito'), ('error', 'Error'), ('timeout', 'Timeout'), ('bloqueado', 'Bloqueado')], default='exito', max_length=10, verbose_name='Estado de la captura')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Código de estado HTTP')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Content-Type')),
                ('content_length', models.IntegerField(blank=True, null=True, verbose_name='Longitud del contenido (bytes)')),
                ('encoding', models.CharField(blank=True, max_length=50, verbose_name='Codificación del contenido')),
                ('contenido_html', models.TextField(verbose_name='Contenido HTML crudo')),
                ('hash_sha256', models.CharField(db_index=True, max_length=64, verbose_name='Hash SHA-256 del contenido')),
                ('hash_simplificado', models.CharField(db_index=True, max_length=64, verbose_name='Hash simplificado (sin whitespace)')),
                ('num_palabras', models.IntegerField(blank=True, null=True, verbose_name='Número de palabras')),
                ('num_lineas', models.IntegerField(blank=True, null=True, verbose_name='Número de líneas')),
                ('num_links', models.IntegerField(blank=True, null=True, verbose_name='Número de enlaces')),
                ('tiempo_respuesta_ms', models.IntegerField(blank=True, null=True, verbose_name='Tiempo de respuesta (ms)')),
                ('tamaño_bytes', models.IntegerField(blank=True, null=True, verbose_name='Tamaño en bytes')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('stack_trace', models.TextField(blank=True, verbose_name='Stack trace (si aplica)')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capturas', to='semillas.fuenteweb', verbose_name='Fuente web')),
            ],
            options={
                'verbose_name': 'Captura Cruda',
                'verbose_name_plural': 'Capturas Crudas',
                'ordering': ['-fecha_captura'],
            },
        ),
        migrations.CreateModel(
            name='EventoDeteccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de detección')),
                ('tipo_cambio', models.CharField(choices=[('contenido', 'Cambio de contenido'), ('estructura', 'Cambio de estructura'), ('enlaces', 'Cambio en enlaces'), ('metadatos', 'Cambio en metadatos'), ('error', 'Error en comparación')], max_length=20, verbose_name='Tipo de cambio')),
                ('severidad', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='medio', max_length=10, verbose_name='Severidad del cambio')),
                ('similitud_porcentaje', models.FloatField(verbose_name='Porcentaje de similitud')),
                ('diferencia_palabras', models.IntegerField(verbose_name='Diferencia en palabras')),
                ('diferencia_lineas', models.IntegerField(verbose_name='Diferencia en líneas')),
                ('diferencia_enlaces', models.IntegerField(verbose_name='Diferencia en enlaces')),
                ('hash_anterior', models.CharField(max_length=64, verbose_name='Hash de la captura anterior')),
                ('hash_nuevo', models.CharField(max_length=64, verbose_name='Hash de la captura nueva')),
                ('resumen_cambio', models.TextField(verbose_name='Resumen del cambio')),
                ('fragmentos_cambiados', models.JSONField(default=list, verbose_name='Fragmentos cambiados')),
                ('contexto_anterior', models.TextField(blank=True, verbose_name='Contexto anterior')),
                ('contexto_nuevo', models.TextField(blank=True, verbose_name='Contexto nuevo')),
                ('analizado_por_ia', models.BooleanField(default=False, verbose_name='Analizado por IA')),
                ('etiquetas_automaticas', models.JSONField(default=list, verbose_name='Etiquetas automáticas')),
                ('captura_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_como_anterior', to='captura.capturacruda', verbose_name='Captura anterior')),
                ('captura_nueva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_como_nueva', to='captura.capturacruda', verbose_name='Captura nueva')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_deteccion', to='semillas.fuenteweb', verbose_name='Fuente web')),
            ],
            options={
                'verbose_name': 'Evento de Detección',
                'verbose_name_plural': 'Eventos de Detección',
                'ordering': ['-fecha_deteccion'],
            },
        ),
        migrations.AddIndex(
            model_name='capturacruda',
            index=models.Index(fields=['fuente', '-fecha_captura'], name='captura_cap_fuente__5bddf3_idx'),
        ),
        migrations.AddIndex(
            model_name='capturacruda',
            index=models.Index(fields=['hash_sha256'], name='captura_cap_hash_sh_6a920a_idx'),
        ),
        migrations.AddIndex(
            model_name='capturacruda',
            index=models.Index(fields=['estado', 'fecha_captura'], name='captura_cap_estado_06fd85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='capturacruda',
            unique_together={('fuente', 'hash_sha256')},
        ),
        migrations.AddIndex(
            model_name='eventodeteccion',
            index=models.Index(fields=['fuente', '-fecha_deteccion'], name='captura_eve_fuente__e6ec8b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventodeteccion',
            index=models.Index(fields=['tipo_cambio', 'severidad'], name='captura_eve_tipo_ca_78ea0d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventodeteccion',
            index=models.Index(fields=['similitud_porcentaje'], name='captura_eve_similit_692b15_idx'),
        ),
    ]
