# Generated by Django 5.0.6 on 2026-09-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_intelligence', '0003_motorai_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoraicontrol',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
