# Generated by Django 5.2.10 on 2026-03-30 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=50, unique=True, verbose_name='ID de campaña en Meta')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la campaña')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('PAUSED', 'Pausada'), ('ARCHIVED', 'Archivada'), ('DELETED', 'Eliminada')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('objective', models.CharField(blank=True, max_length=50, verbose_name='Objetivo de la campaña')),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Presupuesto diario')),
                ('created_at_meta', models.DateField(blank=True, null=True, verbose_name='Fecha de creación en Meta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Campaña Meta',
                'verbose_name_plural': 'Campañas Meta',
                'ordering': ['-created_at_meta', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MetaCampaignInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('impressions', models.IntegerField(default=0, verbose_name='Impresiones')),
                ('clicks', models.IntegerField(default=0, verbose_name='Clics')),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gasto')),
                ('reach', models.IntegerField(default=0, verbose_name='Alcance')),
                ('cpc', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Costo por clic (CPC)')),
                ('ctr', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Tasa de clics (CTR)')),
                ('frequency', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Frecuencia')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de sincronización')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='meta_ads.metacampaign', verbose_name='Campaña')),
            ],
            options={
                'verbose_name': 'Métrica diaria de campaña',
                'verbose_name_plural': 'Métricas diarias de campañas',
                'ordering': ['-date', 'campaign'],
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
