# Generated by Django 5.2.10 on 2026-04-23 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=50, unique=True, verbose_name='ID del anuncio en Meta')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del anuncio')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('PAUSED', 'Pausado'), ('ARCHIVED', 'Archivado'), ('DELETED', 'Eliminado')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('adset_id', models.CharField(blank=True, max_length=50, verbose_name='ID del conjunto de anuncios')),
                ('adset_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre del conjunto de anuncios')),
                ('creative_id', models.CharField(blank=True, max_length=50, verbose_name='ID de la creatividad')),
                ('creative_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre de la creatividad')),
                ('creative_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de creatividad')),
                ('impressions', models.IntegerField(default=0, verbose_name='Impresiones')),
                ('clicks', models.IntegerField(default=0, verbose_name='Clics')),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gasto')),
                ('ctr', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Tasa de clics (CTR)')),
                ('cpc', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Costo por clic (CPC)')),
                ('created_at_meta', models.DateField(blank=True, null=True, verbose_name='Fecha de creación en Meta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='meta_ads.metacampaign', verbose_name='Campaña')),
            ],
            options={
                'verbose_name': 'Anuncio Meta',
                'verbose_name_plural': 'Anuncios Meta',
                'ordering': ['-created_at_meta', 'name'],
            },
        ),
    ]
