# Generated by Django 5.2.10 on 2026-04-15 20:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID de la app')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre descriptivo')),
                ('level', models.IntegerField(choices=[(1, 'Nivel 1 - Memoria pura'), (2, 'Nivel 2 - Memoria + Conocimiento'), (3, 'Nivel 3 - Memoria + Conocimiento + Métricas')], default=1, verbose_name='Nivel de la app')),
                ('capabilities', models.JSONField(default=dict, help_text='JSON con capacidades habilitadas: memory, knowledge_base, metrics, projects', verbose_name='Capacidades')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('config', models.JSONField(default=dict, verbose_name='Configuración adicional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de App',
                'verbose_name_plural': 'Configuraciones de Apps',
                'db_table': 'intelligence_app_configs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del rol')),
                ('level', models.IntegerField(choices=[(1, 'Nivel 1 - Memoria pura'), (2, 'Nivel 2 - Memoria + Conocimiento'), (3, 'Nivel 3 - Memoria + Conocimiento + Métricas')], default=1, verbose_name='Nivel de acceso')),
                ('capabilities', models.JSONField(default=dict, help_text='JSON con capacidades específicas: memory, knowledge_base, metrics, projects', verbose_name='Capacidades')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'intelligence_roles',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255, verbose_name='ID de sesión')),
                ('messages', models.JSONField(default=list, help_text='Lista de objetos mensaje con role, content, timestamp', verbose_name='Mensajes')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadatos de la conversación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sesión activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='Último mensaje')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='intelligence.appconfig', verbose_name='App')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'db_table': 'intelligence_conversations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadatos adicionales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='intelligence.role', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'intelligence_users',
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=500, verbose_name='Sujeto')),
                ('relation', models.CharField(max_length=200, verbose_name='Relación')),
                ('object', models.CharField(max_length=500, verbose_name='Objeto')),
                ('confidence', models.FloatField(default=1.0, help_text='Confianza en la exactitud del hecho (0.0 a 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Confianza')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadatos adicionales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_facts', to='intelligence.conversation', verbose_name='Conversación fuente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='intelligence.user', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Hecho',
                'verbose_name_plural': 'Hechos',
                'db_table': 'intelligence_facts',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='intelligence.user', verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='intelligenc_phone_e86593_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='intelligenc_email_4f9591_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='intelligenc_created_d21e90_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False)), fields=('phone',), name='unique_phone_when_not_null'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='unique_email_when_not_null'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('phone__isnull', False), ('email__isnull', False), _connector='OR'), name='phone_or_email_required'),
        ),
        migrations.AddIndex(
            model_name='fact',
            index=models.Index(fields=['user', 'relation'], name='intelligenc_user_id_459ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='fact',
            index=models.Index(fields=['subject', 'relation', 'object'], name='intelligenc_subject_39f2b3_idx'),
        ),
        migrations.AddIndex(
            model_name='fact',
            index=models.Index(fields=['created_at'], name='intelligenc_created_bb24b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.UniqueConstraint(fields=('user', 'subject', 'relation', 'object'), name='unique_fact_per_user'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'app', 'created_at'], name='intelligenc_user_id_5347f5_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='intelligenc_last_me_288d60_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('user', 'app', 'session_id'), name='unique_session_per_user_app'),
        ),
    ]
