# Generated by Django 5.2.10 on 2026-04-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='context_summary',
            field=models.TextField(blank=True, default='', help_text='Resumen de conversaciones anteriores para mantener contexto histórico', verbose_name='Resumen de contexto'),
        ),
    ]
