# Generated by Django 5.2.10 on 2026-04-15 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_conversation_context_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Nombre único de la colección (ej: 'propiedades_propifai')", max_length=100, unique=True, verbose_name='Nombre de colección')),
                ('source_sql', models.TextField(help_text='Query SQL contra Azure SQL que retorna id, y campos para embedding', verbose_name='SQL de origen')),
                ('embedding_fields', models.JSONField(default=list, help_text="Lista de campos a concatenar (ej: ['titulo', 'descripcion', 'zona'])", verbose_name='Campos para embedding')),
                ('access_level', models.IntegerField(choices=[(1, 'Nivel 1 - Memoria pura'), (2, 'Nivel 2 - Memoria + Conocimiento'), (3, 'Nivel 3 - Memoria + Conocimiento + Métricas')], default=2, verbose_name='Nivel de acceso mínimo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronización')),
                ('last_sync_count', models.IntegerField(default=0, verbose_name='Registros en última sincro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Colección Vectorial',
                'verbose_name_plural': 'Colecciones Vectoriales',
                'db_table': 'intelligence_collections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.CharField(help_text='ID original en tabla origen', max_length=200, verbose_name='ID original')),
                ('content', models.TextField(help_text='Texto concatenado de los campos para embedding', verbose_name='Contenido embeddeado')),
                ('embedding', models.BinaryField(blank=True, help_text='Vector de 384 dimensiones (all-MiniLM-L6-v2)', max_length='max', null=True, verbose_name='Vector embedding')),
                ('metadata_json', models.JSONField(default=dict, help_text='Datos adicionales (precio, zona, fecha, etc.)', verbose_name='Metadatos')),
                ('content_hash', models.CharField(help_text='SHA256 del contenido para detectar cambios', max_length=64, verbose_name='Hash del contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='intelligence.intelligencecollection', verbose_name='Colección')),
            ],
            options={
                'verbose_name': 'Documento Vectorial',
                'verbose_name_plural': 'Documentos Vectoriales',
                'db_table': 'intelligence_documents',
                'indexes': [models.Index(fields=['collection', 'content_hash'], name='intelligenc_collect_d10e4d_idx'), models.Index(fields=['collection', 'created_at'], name='intelligenc_collect_534e43_idx'), models.Index(fields=['content_hash'], name='intelligenc_content_98e37e_idx')],
                'constraints': [models.UniqueConstraint(fields=('collection', 'source_id'), name='unique_document_per_collection')],
            },
        ),
    ]
