# Generated by Django 5.2.10 on 2026-04-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0004_add_description_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.RemoveField(
            model_name='role',
            name='level',
        ),
        migrations.AddField(
            model_name='role',
            name='allowed_levels',
            field=models.JSONField(default=list, help_text='Lista de niveles permitidos para este rol (ej: [1, 2, 3])', verbose_name='Niveles permitidos'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='level',
            field=models.IntegerField(choices=[(1, 'Nivel 1 - Memoria pura'), (2, 'Nivel 2 - Memoria + Conocimiento'), (3, 'Nivel 3 - Memoria + Conocimiento + Métricas'), (4, 'Nivel 4 - Acceso completo + Analytics'), (5, 'Nivel 5 - Administrador total')], default=1, help_text='Nivel de acceso (1-5) según SPEC-005', verbose_name='Nivel de la app'),
        ),
        # Constraints removidas por compatibilidad con Django 5.0.6
        # Las constraints con condition no son compatibles en esta versión
    ]
