# Generated by Django 5.2.10 on 2026-04-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0005_update_models_for_spec005'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligencecollection',
            name='apps_con_acceso',
            field=models.JSONField(default=list, help_text='Lista de IDs de apps que pueden acceder a esta colección', verbose_name='Apps con acceso'),
        ),
        migrations.AddField(
            model_name='intelligencecollection',
            name='roles_con_acceso',
            field=models.JSONField(default=list, help_text='Lista de IDs de roles que pueden acceder a esta colección', verbose_name='Roles con acceso'),
        ),
        migrations.AlterField(
            model_name='intelligencecollection',
            name='access_level',
            field=models.IntegerField(choices=[(1, 'Nivel 1 - Memoria pura'), (2, 'Nivel 2 - Memoria + Conocimiento'), (3, 'Nivel 3 - Memoria + Conocimiento + Métricas'), (4, 'Nivel 4 - Acceso completo + Analytics'), (5, 'Nivel 5 - Administrador total')], default=2, help_text='Nivel mínimo requerido para acceder a esta colección (1-5)', verbose_name='Nivel de acceso mínimo'),
        ),
    ]
