# Generated by Django 5.2.10 on 2026-04-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0006_update_collection_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intelligencedocument',
            name='metadata_json',
        ),
        migrations.AddField(
            model_name='intelligencecollection',
            name='display_fields',
            field=models.JSONField(default=list, help_text='Lista de campos (nombres reales) a mostrar en resultados de búsqueda', verbose_name='Campos a mostrar'),
        ),
        migrations.AddField(
            model_name='intelligencecollection',
            name='field_definitions',
            field=models.JSONField(default=dict, help_text="Diccionario con definición de TODOS los campos de la tabla: {'nombre_campo': {'type': 'string', 'nullable': false, ...}}", verbose_name='Definiciones de campos'),
        ),
        migrations.AddField(
            model_name='intelligencecollection',
            name='filter_fields',
            field=models.JSONField(default=list, help_text='Lista de campos (nombres reales) que se pueden usar como filtros', verbose_name='Campos filtrables'),
        ),
        migrations.AddField(
            model_name='intelligencecollection',
            name='table_name',
            field=models.CharField(blank=True, help_text="Nombre exacto de la tabla en Azure SQL (ej: 'propiedadraw'). Dejar vacío para colecciones manuales.", max_length=200, null=True, verbose_name='Nombre de tabla'),
        ),
        migrations.AddField(
            model_name='intelligencedocument',
            name='field_values',
            field=models.JSONField(default=dict, help_text='Diccionario con nombres REALES de campos y sus valores de la tabla origen', verbose_name='Valores de campos'),
        ),
        migrations.AlterField(
            model_name='intelligencecollection',
            name='embedding_fields',
            field=models.JSONField(default=list, help_text="Lista de campos (nombres reales) usados para embedding (ej: ['titulo', 'descripcion', 'zona'])", verbose_name='Campos para embedding'),
        ),
        migrations.AlterField(
            model_name='intelligencecollection',
            name='source_sql',
            field=models.TextField(blank=True, help_text='Query SQL contra Azure SQL que retorna id, y campos para embedding (opcional, se genera automáticamente si está vacío)', verbose_name='SQL de origen'),
        ),
        migrations.AlterField(
            model_name='intelligencedocument',
            name='source_id',
            field=models.CharField(help_text='Valor del campo ID en la tabla origen', max_length=200, verbose_name='ID original'),
        ),
        # NOTA: Las restricciones unique_phone_when_not_null, unique_email_when_not_null y phone_or_email_required
        # ya existen en la base de datos desde migraciones anteriores, por lo que se omiten para evitar errores.
    ]
