# Generated by Django 5.2.10 on 2026-04-23 18:08

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0007_remove_intelligencedocument_metadata_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodicMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_message', models.TextField(verbose_name='Mensaje del usuario')),
                ('user_message_embedding', models.BinaryField(blank=True, help_text='Vector de 384 dimensiones para búsqueda semántica', null=True, verbose_name='Embedding del mensaje')),
                ('assistant_response', models.TextField(verbose_name='Respuesta del asistente')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Momento de la interacción')),
                ('episode_type', models.CharField(choices=[('property_search', 'Búsqueda de propiedad'), ('property_detail', 'Consulta de detalle'), ('price_inquiry', 'Consulta de precio'), ('matching', 'Matching oferta-demanda'), ('acm_analysis', 'Análisis ACM'), ('general', 'Consulta general'), ('fact_extraction', 'Extracción de hecho'), ('user_preference', 'Preferencia del usuario')], db_index=True, default='general', max_length=50, verbose_name='Tipo de episodio')),
                ('intent_detected', models.CharField(blank=True, default='', max_length=100, verbose_name='Intención detectada')),
                ('context', models.JSONField(blank=True, default=dict, help_text="Almacena:\n            - entities: {districts, property_types, price_range, ...}\n            - topics: [temas detectados]\n            - sentiment: positivo/neutral/negativo\n            - user_actions: [acciones del usuario]\n        ", verbose_name='Contexto del episodio')),
                ('rag_context_used', models.JSONField(blank=True, default=dict, help_text="Almacena:\n            - collections_queried: [nombres de colecciones]\n            - documents_retrieved: [{id, title, score}]\n            - search_type: vector | text | hybrid\n            - total_results: número total de resultados\n        ", verbose_name='Contexto RAG utilizado')),
                ('memory_context_used', models.JSONField(blank=True, default=dict, help_text="Almacena:\n            - facts_retrieved: [hechos usados]\n            - conversations_retrieved: [conversaciones usadas]\n        ", verbose_name='Contexto de memoria utilizado')),
                ('feedback', models.JSONField(blank=True, default=dict, help_text="Almacena:\n            - thumbs_up: bool | null\n            - thumbs_down: bool | null\n            - user_comment: str | null\n            - collected_at: timestamp | null\n        ", verbose_name='Feedback del usuario')),
                ('latency_ms', models.IntegerField(blank=True, help_text='Tiempo de generación de la respuesta en milisegundos', null=True, verbose_name='Latencia (ms)')),
                ('importance_score', models.FloatField(default=0.5, help_text='0.0 = trivial, 1.0 = muy importante. Se calcula automáticamente.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Puntuación de importancia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodic_memories', to='intelligence.conversation', verbose_name='Conversación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodic_memories', to='intelligence.user', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Memoria Episódica',
                'verbose_name_plural': 'Memorias Episódicas',
                'db_table': 'intelligence_episodic_memory',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='intelligenc_user_id_90b2ab_idx'), models.Index(fields=['user', 'episode_type'], name='intelligenc_user_id_ce8c65_idx'), models.Index(fields=['user', 'importance_score'], name='intelligenc_user_id_cc1eba_idx'), models.Index(fields=['timestamp'], name='intelligenc_timesta_1e5074_idx')],
            },
        ),
    ]
