# Generated by Django 5.2.10 on 2026-04-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0009_user_first_name_user_last_login_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Nombre de usuario'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False)), fields=('phone',), name='unique_phone_when_not_null'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='unique_email_when_not_null'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('phone__isnull', False), ('email__isnull', False), _connector='OR'), name='phone_or_email_required'),
        ),
    ]
