"""
Generated by Django 5.0.6 on 2026-05-04

Agrega el campo database_alias al modelo IntelligenceCollection
para especificar qué alias de base de datos usar (ej: 'default', 'propifai').
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0014_intelligence_levels_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligencecollection',
            name='database_alias',
            field=models.CharField(
                default='default',
                max_length=50,
                verbose_name='Alias de base de datos',
                help_text="Alias de la conexión de base de datos en Django settings (ej: 'default', 'propifai')"
            ),
        ),
    ]
