# Generated by Django 5.2.10 on 2026-04-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acm', '0001_initial'),
        ('intelligence', '0010_alter_user_username_user_unique_phone_when_not_null_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='acmlink',
            new_name='acm_links_user_id_123283_idx',
            old_name='acm_links_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='acmlink',
            new_name='acm_links_created_4ebf67_idx',
            old_name='acm_links_created_idx',
        ),
        migrations.AddField(
            model_name='acmlink',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código ACM (ej: ACM9342453)'),
        ),
        migrations.AddField(
            model_name='acmlink',
            name='origen',
            field=models.CharField(choices=[('pdf', 'Generar PDF'), ('compartir', 'Compartir WhatsApp'), ('ambos', 'Ambos')], default='compartir', max_length=20, verbose_name='Origen del guardado'),
        ),
        migrations.AddIndex(
            model_name='acmlink',
            index=models.Index(fields=['codigo'], name='acm_links_codigo_f4a614_idx'),
        ),
    ]
