# Generated by Django 5.2.10 on 2026-02-12 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigracionPendiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campo_bd', models.CharField(max_length=100)),
                ('titulo_display', models.CharField(max_length=150)),
                ('tipo_dato', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('ejecutada_en', models.DateTimeField(blank=True, null=True)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Migración Pendiente',
                'verbose_name_plural': 'Migraciones Pendientes',
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CampoDinamico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campo_bd', models.CharField(max_length=100, unique=True)),
                ('titulo_display', models.CharField(max_length=150)),
                ('tipo_dato', models.CharField(max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campo Dinámico',
                'verbose_name_plural': 'Campos Dinámicos',
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MapeoFuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fuente', models.CharField(max_length=100)),
                ('portal_origen', models.CharField(max_length=50)),
                ('mapeos_confirmados', models.JSONField(default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mapeo de Fuente',
                'verbose_name_plural': 'Mapeos de Fuentes',
                'unique_together': {('nombre_fuente', 'portal_origen')},
            },
        ),
        migrations.CreateModel(
            name='PropiedadRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente_excel', models.CharField(max_length=100)),
                ('fecha_ingesta', models.DateTimeField(auto_now_add=True)),
                ('tipo_propiedad', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('metros_cuadrados', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('habitaciones', models.IntegerField(blank=True, null=True)),
                ('banos', models.IntegerField(blank=True, null=True)),
                ('estacionamientos', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url_fuente', models.URLField(blank=True, max_length=500, null=True)),
                ('atributos_extras', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Propiedad Raw',
                'verbose_name_plural': 'Propiedades Raw',
                'indexes': [models.Index(fields=['fuente_excel', 'fecha_ingesta'], name='ingestas_pr_fuente__182211_idx'), models.Index(fields=['tipo_propiedad'], name='ingestas_pr_tipo_pr_feed2f_idx'), models.Index(fields=['precio_usd'], name='ingestas_pr_precio__02bba6_idx')],
            },
        ),
    ]
