# Generated by Django 5.0.6 on 2026-02-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campodinamico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mapeofuente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='migracionpendiente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='propiedadraw',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
