# Generated by Django 5.2.10 on 2026-02-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestas', '0002_alter_campodinamico_id_alter_mapeofuente_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedadraw',
            name='agente_inmobiliario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='antiguedad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Antigüedad'),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='area_construida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área Construida (m²)'),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='area_terreno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área de Terreno (m²)'),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='coordenadas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='distrito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='email_agente',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='energia_electrica',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicación'),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='id_propiedad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de la Propiedad'),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='imagenes_propiedad',
            field=models.TextField(blank=True, null=True, verbose_name='Imágenes de la Propiedad'),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='numero_banos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Baños'),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='numero_cocheras',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Cocheras'),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='numero_habitaciones',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Habitaciones'),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='numero_pisos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Pisos'),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='oficina_remax',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='portal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='servicio_agua',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='servicio_drenaje',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='servicio_gas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='telefono_agente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='url_propiedad',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='propiedadraw',
            index=models.Index(fields=['portal'], name='ingestas_pr_portal_4580e6_idx'),
        ),
        migrations.AddIndex(
            model_name='propiedadraw',
            index=models.Index(fields=['departamento', 'provincia', 'distrito'], name='ingestas_pr_departa_f9d42a_idx'),
        ),
    ]
