# Generated by Django 5.2.10 on 2026-02-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestas', '0003_propiedadraw_agente_inmobiliario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadraw',
            name='area_construida',
            field=models.DecimalField(blank=True, db_column='area_construida_m2', decimal_places=2, max_digits=10, null=True, verbose_name='Área Construida (m²)'),
        ),
        migrations.AlterField(
            model_name='propiedadraw',
            name='area_terreno',
            field=models.DecimalField(blank=True, db_column='area_de_terreno_m2', decimal_places=2, max_digits=10, null=True, verbose_name='Área de Terreno (m²)'),
        ),
        migrations.AlterField(
            model_name='propiedadraw',
            name='email_agente',
            field=models.EmailField(blank=True, db_column='email_del_agente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadraw',
            name='fecha_publicacion',
            field=models.DateField(blank=True, db_column='fecha_de_publicacion', null=True, verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='propiedadraw',
            name='id_propiedad',
            field=models.CharField(blank=True, db_column='id_de_la_propiedad', max_length=50, null=True, verbose_name='ID de la Propiedad'),
        ),
        migrations.AlterField(
            model_name='propiedadraw',
            name='imagenes_propiedad',
            field=models.TextField(blank=True, db_column='imagenes_de_la_propiedad', null=True, verbose_name='Imágenes de la Propiedad'),
        ),
        migrations.AlterField(
            model_name='propiedadraw',
            name='numero_banos',
            field=models.IntegerField(blank=True, db_column='numero_de_banos', null=True, verbose_name='Número de Baños'),
        ),
        migrations.AlterField(
            model_name='propiedadraw',
            name='numero_cocheras',
            field=models.IntegerField(blank=True, db_column='numero_de_cocheras', null=True, verbose_name='Número de Cocheras'),
        ),
        migrations.AlterField(
            model_name='propiedadraw',
            name='numero_habitaciones',
            field=models.IntegerField(blank=True, db_column='numero_de_habitaciones', null=True, verbose_name='Número de Habitaciones'),
        ),
        migrations.AlterField(
            model_name='propiedadraw',
            name='numero_pisos',
            field=models.IntegerField(blank=True, db_column='numero_de_pisos', null=True, verbose_name='Número de Pisos'),
        ),
        migrations.AlterField(
            model_name='propiedadraw',
            name='servicio_agua',
            field=models.CharField(blank=True, db_column='servicio_de_agua', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadraw',
            name='servicio_drenaje',
            field=models.CharField(blank=True, db_column='servicio_de_drenaje', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadraw',
            name='servicio_gas',
            field=models.CharField(blank=True, db_column='servicio_de_gas', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadraw',
            name='telefono_agente',
            field=models.CharField(blank=True, db_column='telefono_del_agente', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadraw',
            name='url_propiedad',
            field=models.URLField(blank=True, db_column='url_de_la_propiedad', max_length=500, null=True),
        ),
    ]
