# Generated by Django 5.2.10 on 2026-02-20 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestas', '0004_change_fecha_publicacion_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedadraw',
            name='banos',
        ),
        migrations.RemoveField(
            model_name='propiedadraw',
            name='estacionamientos',
        ),
        migrations.RemoveField(
            model_name='propiedadraw',
            name='habitaciones',
        ),
        migrations.RemoveField(
            model_name='propiedadraw',
            name='metros_cuadrados',
        ),
        migrations.RemoveField(
            model_name='propiedadraw',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='propiedadraw',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='propiedadraw',
            name='url_fuente',
        ),
    ]
