# Generated by Django 5.2.10 on 2026-02-21 03:23

import ingestas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestas', '0005_remove_old_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadraw',
            name='atributos_extras',
            field=models.JSONField(blank=True, default=ingestas.models.PropiedadRaw.default_atributos_extras, null=True),
        ),
    ]
