# Generated by Django 5.2.10 on 2026-02-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestas', '0006_fix_atributos_extras_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedadraw',
            name='estado_propiedad',
            field=models.CharField(blank=True, choices=[('en_publicacion', 'En publicación'), ('vendido', 'Vendido'), ('reservado', 'Reservado'), ('retirado', 'Retirado')], default='en_publicacion', max_length=20, null=True, verbose_name='Estado de la propiedad'),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='fecha_venta',
            field=models.DateField(blank=True, help_text='Fecha en que se vendió la propiedad', null=True, verbose_name='Fecha de venta'),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='precio_final_venta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio final al que se vendió la propiedad', max_digits=15, null=True, verbose_name='Precio final de venta (USD)'),
        ),
    ]
