# Generated by Django 5.2.10 on 2026-03-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestas', '0007_propiedadraw_estado_propiedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadraw',
            name='tipo_propiedad',
            field=models.CharField(blank=True, choices=[('Terreno', 'Terreno'), ('Casa', 'Casa'), ('Departamento', 'Departamento'), ('Oficina', 'Oficina'), ('Otros', 'Otros')], max_length=20, null=True, verbose_name='Tipo de propiedad'),
        ),
    ]
