# Generated by Django 5.2.10 on 2026-03-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestas', '0008_estandarizar_tipo_propiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedadraw',
            name='identificador_externo',
            field=models.CharField(blank=True, help_text='ID de la propiedad en la base de datos original de la fuente', max_length=100, null=True, verbose_name='Identificador Externo'),
        ),
    ]
