# Generated by Django 5.2.10 on 2026-03-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestas', '0009_propiedadraw_identificador_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedadraw',
            name='subtipo_propiedad',
            field=models.CharField(blank=True, help_text='Ej: Casa de campo, Departamento dúplex, Oficina ejecutiva, etc.', max_length=50, null=True, verbose_name='Subtipo de propiedad'),
        ),
    ]
