# Generated by Django 5.0.6 on 2026-03-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestas', '0010_add_subtipo_propiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedadraw',
            name='condicion',
            field=models.CharField(blank=True, choices=[('compra', 'Compra'), ('alquiler', 'Alquiler'), ('ambos', 'Compra y Alquiler'), ('no_especificado', 'No Especificado')], default='no_especificado', help_text='Indica si la propiedad está en venta, alquiler o ambos', max_length=20, null=True, verbose_name='Condición (Venta/Alquiler)'),
        ),
        migrations.AddField(
            model_name='propiedadraw',
            name='propiedad_verificada',
            field=models.BooleanField(default=False, help_text='Indica si los campos están óptimos para el análisis del ACM', verbose_name='Propiedad Verificada'),
        ),
    ]
