# Generated by Django 5.2.10 on 2026-03-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestas', '0011_add_condicion_propiedad_verificada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadraw',
            name='condicion',
            field=models.CharField(blank=True, choices=[('venta', 'Venta'), ('compra', 'Compra'), ('alquiler', 'Alquiler'), ('anticresis', 'Anticresis'), ('ambos', 'Compra y Alquiler'), ('no_especificado', 'No Especificado')], default='no_especificado', help_text='Indica si la propiedad está en venta, alquiler, anticresis o ambos', max_length=20, null=True, verbose_name='Condición (Venta/Alquiler)'),
        ),
    ]
