# Generated by Django 5.0.6 on 2026-09-07 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestas', '0016_propiedad_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionFuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(db_index=True, max_length=64)),
                ('misses', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(default='activa', max_length=20)),
                ('first_missing_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scraping_publicacion_fuente',
            },
        ),
        migrations.CreateModel(
            name='ScrapingCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=100)),
                ('raw', models.JSONField(default=dict)),
                ('page', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('save_outcome', models.CharField(default='', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scraping_candidates',
            },
        ),
        migrations.AddField(
            model_name='ejecucionportal',
            name='discovery',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ejecucionportal',
            name='source_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ejecucionportal',
            name='source_key',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='scrapinglog',
            name='contexto',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scrapinglog',
            name='evento',
            field=models.CharField(db_index=True, default='message', max_length=80),
        ),
        migrations.AddField(
            model_name='publicacionfuente',
            name='last_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestas.ejecucionportal'),
        ),
        migrations.AddField(
            model_name='publicacionfuente',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuentes_observadas', to='ingestas.propiedadescompetencia'),
        ),
        migrations.AddField(
            model_name='scrapingcandidate',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='ingestas.ejecucionportal'),
        ),
        migrations.AddConstraint(
            model_name='publicacionfuente',
            constraint=models.UniqueConstraint(fields=('source_key', 'propiedad'), name='scrap_source_property_uq'),
        ),
        migrations.AddIndex(
            model_name='scrapingcandidate',
            index=models.Index(fields=['run', 'page', 'status'], name='scrap_candidate_pending_idx'),
        ),
        migrations.AddConstraint(
            model_name='scrapingcandidate',
            constraint=models.UniqueConstraint(fields=('run', 'source_id'), name='scrap_run_candidate_uq'),
        ),
    ]
