# Generated by Django 5.0.6 on 2026-09-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestas', '0017_scraping_integrity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingWorker',
            fields=[
                ('identity', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('heartbeat_at', models.DateTimeField()),
                ('revision', models.CharField(default='development', max_length=64)),
            ],
            options={
                'db_table': 'scraping_workers',
            },
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
