# Generated by Django 5.0.6 on 2026-09-30 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestas', '0025_revision_correcta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPipelineState',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('cursor', models.BigIntegerField(default=0)),
                ('sweep_finished_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MLObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('snapshot', models.JSONField()),
                ('changes', models.JSONField(default=dict)),
                ('origin', models.CharField(default='save', max_length=40)),
                ('job_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('rule_version', models.CharField(max_length=40)),
                ('reasons', models.JSONField(default=list)),
                ('notes', models.JSONField(default=list)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ml_observations', to='ingestas.propiedadescompetencia')),
            ],
        ),
        migrations.CreateModel(
            name='MLCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('propiedad', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ml_candidate', to='ingestas.propiedadescompetencia')),
                ('latest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ingestas.mlobservation')),
            ],
        ),
        migrations.AddIndex(
            model_name='mlobservation',
            index=models.Index(fields=['status', 'id'], name='ml_obs_pending_idx'),
        ),
        migrations.AddConstraint(
            model_name='mlobservation',
            constraint=models.UniqueConstraint(fields=('propiedad', 'sequence'), name='ml_obs_property_sequence'),
        ),
    ]
