# Generated by Django 5.0.6 on 2026-09-30 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestas', '0026_ml_candidates'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLZoneVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_key', models.BigIntegerField(db_index=True)),
                ('sequence', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='mlpipelinestate',
            name='payload',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='MLIdentityPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_signature', models.CharField(max_length=64)),
                ('right_signature', models.CharField(max_length=64)),
                ('rule_version', models.CharField(max_length=40)),
                ('status', models.CharField(db_index=True, default='possible', max_length=16)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('evidence', models.JSONField(default=list)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('decision_stale', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ml_identity_left', to='ingestas.propiedadescompetencia')),
                ('left_observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ingestas.mlobservation')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ml_identity_right', to='ingestas.propiedadescompetencia')),
                ('right_observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ingestas.mlobservation')),
            ],
        ),
        migrations.CreateModel(
            name='MLIdentityDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=16)),
                ('reason', models.TextField()),
                ('actor', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('left_observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ingestas.mlobservation')),
                ('right_observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ingestas.mlobservation')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='ingestas.mlidentitypair')),
            ],
        ),
        migrations.CreateModel(
            name='MLSpatialAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_hash', models.CharField(max_length=64)),
                ('rule_version', models.CharField(max_length=40)),
                ('state', models.CharField(db_index=True, max_length=32)),
                ('matching_versions', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spatial_assessments', to='ingestas.mlobservation')),
            ],
        ),
        migrations.AddField(
            model_name='mlcandidate',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ingestas.mlspatialassessment'),
        ),
        migrations.AddConstraint(
            model_name='mlzoneversion',
            constraint=models.UniqueConstraint(fields=('zone_key', 'sequence'), name='ml_zone_sequence_uq'),
        ),
        migrations.AddField(
            model_name='mlspatialassessment',
            name='zone_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ingestas.mlzoneversion'),
        ),
        migrations.AddConstraint(
            model_name='mlidentitypair',
            constraint=models.UniqueConstraint(fields=('left', 'right'), name='ml_identity_pair_uq'),
        ),
        migrations.AddConstraint(
            model_name='mlidentitypair',
            constraint=models.CheckConstraint(check=models.Q(('left__lt', models.F('right'))), name='ml_identity_pair_order'),
        ),
        migrations.AddConstraint(
            model_name='mlspatialassessment',
            constraint=models.UniqueConstraint(fields=('observation', 'catalog_hash', 'rule_version'), name='ml_spatial_version_uq'),
        ),
    ]
