# Generated by Django 5.0.6 on 2026-02-21 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestas', '0006_fix_atributos_extras_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('coordenadas', models.JSONField(help_text='Lista de coordenadas [[lat,lng], ...] que definen el polígono')),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, help_text='Área total en metros cuadrados', max_digits=15, null=True)),
                ('precio_promedio_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('desviacion_estandar_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cantidad_propiedades_analizadas', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('color_fill', models.CharField(default='#2196F3', help_text='Color HEX para relleno', max_length=7)),
                ('color_borde', models.CharField(default='#1976D2', help_text='Color HEX para borde', max_length=7)),
                ('opacidad', models.FloatField(default=0.3, help_text='Opacidad del polígono (0-1)')),
            ],
            options={
                'verbose_name': 'Zona de Valor',
                'verbose_name_plural': 'Zonas de Valor',
                'ordering': ['nombre_zona'],
            },
        ),
        migrations.CreateModel(
            name='PropiedadValoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_m2', models.DecimalField(blank=True, decimal_places=2, help_text='precio_venta / metros_cuadrados', max_digits=15, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('metros_cuadrados', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('es_comparable', models.BooleanField(default=True, help_text='Indica si la propiedad es comparable para análisis')),
                ('factor_ajuste', models.DecimalField(decimal_places=4, default=1.0, help_text='Factor de ponderación para cálculos', max_digits=5)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('metodo_calculo', models.CharField(choices=[('directo', 'Cálculo Directo'), ('ponderado', 'Ponderado por Antigüedad'), ('ajustado', 'Ajustado por Tipo'), ('estimado', 'Estimado por Zona')], default='directo', max_length=50)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='ingestas.propiedadraw')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades_valoradas', to='cuadrantizacion.zonavalor')),
            ],
            options={
                'verbose_name': 'Valoración de Propiedad',
                'verbose_name_plural': 'Valoraciones de Propiedades',
                'unique_together': {('propiedad', 'zona')},
                'indexes': [models.Index(fields=['precio_m2'], name='cuadrantizac_precio__idx'), models.Index(fields=['es_comparable'], name='cuadrantizac_es_comp_5e4c8b_idx'), models.Index(fields=['zona', 'fecha_calculo'], name='cuadrantizac_zona_id_9c8e5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecioZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('precio_promedio_m2', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cantidad_propiedades', models.IntegerField()),
                ('desviacion_estandar', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fuente_datos', models.CharField(choices=[('cálculo_automático', 'Cálculo Automático'), ('manual', 'Ingreso Manual'), ('actualización_masiva', 'Actualización Masiva')], default='cálculo_automático', max_length=100)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='cuadrantizacion.zonavalor')),
            ],
            options={
                'verbose_name': 'Historial de Precio de Zona',
                'verbose_name_plural': 'Historial de Precios de Zona',
                'ordering': ['zona', '-fecha_registro'],
                'indexes': [models.Index(fields=['zona', 'fecha_registro'], name='cuadrantizac_zona_id_8c5b8c_idx')],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_propiedad', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('terreno', 'Terreno'), ('local', 'Local Comercial'), ('oficina', 'Oficina'), ('otro', 'Otro')], max_length=50)),
                ('cantidad_propiedades', models.IntegerField(default=0)),
                ('precio_promedio_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('precio_mediano_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('precio_minimo_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('precio_maximo_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('desviacion_estandar', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('habitaciones_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('banos_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('antiguedad_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('metros_cuadrados_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='cuadrantizacion.zonavalor')),
            ],
            options={
                'verbose_name': 'Estadística de Zona por Tipo',
                'verbose_name_plural': 'Estadísticas de Zona por Tipo',
                'unique_together': {('zona', 'tipo_propiedad')},
            },
        ),
    ]