# Generated by Django 5.2.10 on 2026-02-24 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrantizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zonavalor',
            options={'ordering': ['nivel', 'nombre_zona'], 'verbose_name': 'Zona de Valor', 'verbose_name_plural': 'Zonas de Valor'},
        ),
        migrations.RenameIndex(
            model_name='historialpreciozona',
            new_name='cuadrantiza_zona_id_ad7e76_idx',
            old_name='cuadrantizac_zona_id_8c5b8c_idx',
        ),
        migrations.RenameIndex(
            model_name='propiedadvaloracion',
            new_name='cuadrantiza_precio__af7548_idx',
            old_name='cuadrantizac_precio__idx',
        ),
        migrations.RenameIndex(
            model_name='propiedadvaloracion',
            new_name='cuadrantiza_es_comp_1e9fe1_idx',
            old_name='cuadrantizac_es_comp_5e4c8b_idx',
        ),
        migrations.RenameIndex(
            model_name='propiedadvaloracion',
            new_name='cuadrantiza_zona_id_0d55c0_idx',
            old_name='cuadrantizac_zona_id_9c8e5c_idx',
        ),
        migrations.AddField(
            model_name='zonavalor',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único para identificación (ej: PE-LIM-LIMA-MIRAFLORES)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zonavalor',
            name='nivel',
            field=models.CharField(choices=[('pais', 'País'), ('departamento', 'Departamento'), ('provincia', 'Provincia'), ('distrito', 'Distrito'), ('zona', 'Zona'), ('subzona', 'Subzona')], default='zona', help_text='Nivel jerárquico de la zona', max_length=20),
        ),
        migrations.AddField(
            model_name='zonavalor',
            name='nombre_oficial',
            field=models.CharField(blank=True, help_text='Nombre oficial según registros gubernamentales', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='zonavalor',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Zona padre en la jerarquía (ej: una zona contiene subzonas)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cuadrantizacion.zonavalor'),
        ),
        migrations.AddIndex(
            model_name='zonavalor',
            index=models.Index(fields=['nivel'], name='cuadrantiza_nivel_0ca678_idx'),
        ),
        migrations.AddIndex(
            model_name='zonavalor',
            index=models.Index(fields=['parent'], name='cuadrantiza_parent__1f18e8_idx'),
        ),
        migrations.AddIndex(
            model_name='zonavalor',
            index=models.Index(fields=['codigo'], name='cuadrantiza_codigo_2fed49_idx'),
        ),
    ]
