# Generated by Django 5.2.10 on 2026-02-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrantizacion', '0002_alter_zonavalor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonavalor',
            name='coordenadas',
            field=models.JSONField(blank=True, help_text='Lista de coordenadas [[lat,lng], ...] que definen el polígono. Solo requerido para subzonas.', null=True),
        ),
    ]
