# Generated by Django 5.0.6 on 2026-10-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrantizacion', '0004_zonavalor_nivel_cuadrante'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapaRasterMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_url', models.CharField(blank=True, default='', help_text='Ruta dentro de /static/ o URL completa de la imagen de la capa.', max_length=500)),
                ('esquinas', models.JSONField(blank=True, default=dict, help_text='{"tl": [lon, lat], "tr": [lon, lat], "br": [lon, lat], "bl": [lon, lat]}')),
                ('opacidad', models.FloatField(default=0.65, help_text='0 = totalmente transparente, 1 = totalmente opaca')),
                ('rotacion', models.FloatField(default=0.0, help_text='Giro en grados (positivo = sentido horario)')),
                ('escala', models.FloatField(default=1.0, help_text='Factor de escala')),
                ('offset_x', models.FloatField(default=0.0, help_text='Desplazamiento horizontal en píxeles de pantalla')),
                ('offset_y', models.FloatField(default=0.0, help_text='Desplazamiento vertical en píxeles de pantalla')),
                ('bloqueado', models.BooleanField(default=False, help_text='Si está bloqueada, la capa no se puede mover ni girar')),
                ('visible', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Capa raster del mapa',
                'verbose_name_plural': 'Capas raster del mapa',
                'ordering': ['orden', 'nombre'],
                'indexes': [models.Index(fields=['activo', 'orden'], name='cuadrantiza_activo_addd6a_idx')],
            },
        ),
    ]
