# Generated by Django 5.0.6 on 2026-10-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrantizacion', '0006_capa_zonificacion_pdm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, default='', max_length=60)),
                ('color', models.CharField(help_text='Color de relleno en formato HEX, tal como aparece en la leyenda.', max_length=7)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zona de uso (leyenda)',
                'verbose_name_plural': 'Zonas de uso (leyenda)',
                'ordering': ['orden', 'codigo'],
            },
        ),
    ]
