# Generated by Django 5.0.6 on 2026-10-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrantizacion', '0008_leyenda_zonificacion_pdm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zonificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(help_text='Origen de la propiedad: propify, remax, properati, ...', max_length=40)),
                ('propiedad_id', models.CharField(help_text='Identificador de la propiedad dentro de su origen', max_length=80)),
                ('propiedad_ref', models.CharField(blank=True, help_text='Código o título de la publicación, para reconocerla rápido', max_length=200, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('codigo', models.CharField(blank=True, default='', max_length=20)),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('categoria', models.CharField(blank=True, default='', max_length=60)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('cobertura', models.FloatField(blank=True, help_text='Proporción de píxeles que coinciden', null=True)),
                ('confianza', models.CharField(blank=True, default='', max_length=10)),
                ('origen_calculo', models.CharField(choices=[('automatico', 'Automático (color del plano)'), ('manual', 'Manual')], default='automatico', max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('verificada', models.BooleanField(default=False, help_text='Marca que alguien confirmó que la propiedad está bien ubicada en esta zona')),
                ('verificada_por', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zonificación de propiedad',
                'verbose_name_plural': 'Zonificaciones de propiedades',
                'ordering': ['fuente', 'propiedad_id'],
                'indexes': [models.Index(fields=['fuente', 'propiedad_id'], name='cuadrantiza_fuente_a19c4d_idx'), models.Index(fields=['codigo'], name='cuadrantiza_codigo_56f62b_idx'), models.Index(fields=['verificada'], name='cuadrantiza_verific_07d8a2_idx')],
                'unique_together': {('fuente', 'propiedad_id')},
            },
        ),
    ]
