# Generated by Django 5.0.6 on 2026-10-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrantizacion', '0009_zonificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapaVectorialMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('geojson_url', models.CharField(help_text='Ruta dentro de /static/ o URL del archivo GeoJSON.', max_length=500)),
                ('propiedad_color', models.CharField(default='color', help_text='Nombre de la propiedad del feature que trae el color de relleno.', max_length=60)),
                ('propiedad_codigo', models.CharField(default='codigo', help_text='Nombre de la propiedad del feature que trae el código de zona.', max_length=60)),
                ('opacidad', models.FloatField(default=0.65, help_text='0 = invisible, 1 = relleno sólido')),
                ('color_borde', models.CharField(blank=True, default='#000000', help_text='Color del borde de los polígonos (vacío = sin borde).', max_length=7)),
                ('grosor_borde', models.FloatField(default=0.4)),
                ('visible', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Capa vectorial del mapa',
                'verbose_name_plural': 'Capas vectoriales del mapa',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
