# Generated by Django 5.0.6 on 2026-10-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrantizacion', '0011_capa_vectorial_zonificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='capavectorialmapa',
            name='escala_ancho',
            field=models.FloatField(default=0.8, help_text='Para líneas: factor que convierte el ancho en puntos del plano al grosor en píxeles de pantalla.'),
        ),
        migrations.AddField(
            model_name='capavectorialmapa',
            name='tamano_rotulo',
            field=models.FloatField(default=10.0, help_text='Tamaño de los rótulos, en píxeles.'),
        ),
        migrations.AddField(
            model_name='capavectorialmapa',
            name='tipo',
            field=models.CharField(choices=[('poligonos', 'Polígonos (zonas de uso)'), ('lineas', 'Líneas (estructura vial)'), ('etiquetas', 'Rótulos (códigos de zona)')], default='poligonos', help_text='Cómo se dibuja el GeoJSON: relleno, líneas o rótulos.', max_length=20),
        ),
        migrations.AddField(
            model_name='capavectorialmapa',
            name='zoom_minimo',
            field=models.IntegerField(default=0, help_text='Zoom mínimo para dibujar la capa (útil en rótulos, que a zoom lejano solo estorban).'),
        ),
    ]
