# Generated by Django 5.0.6 on 2026-10-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrantizacion', '0014_rotulos_mas_grandes'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonauso',
            name='parametros',
            field=models.JSONField(blank=True, default=dict, help_text='Ficha normativa del reglamento para esta zona: bloques por tipología con densidad, lote mínimo, frente, altura, coeficiente, área libre, retiros, alineamiento y estacionamiento.'),
        ),
    ]
