# Generated by Django 5.2.10 on 2026-02-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropifaiProperty',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('codigo_unico_propiedad', models.CharField(blank=True, max_length=11, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('antiquity_years', models.IntegerField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('maintenance_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('has_maintenance', models.BooleanField(default=False)),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('half_bathrooms', models.IntegerField(blank=True, null=True)),
                ('garage_spaces', models.IntegerField(blank=True, null=True)),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('built_area', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('front_measure', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('depth_measure', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('real_address', models.TextField(blank=True, null=True)),
                ('exact_address', models.CharField(blank=True, max_length=512, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=512, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('urbanization', models.CharField(blank=True, max_length=100, null=True)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('zoning', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_ready_for_sale', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_project', models.BooleanField(default=False)),
                ('project_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ascensor', models.CharField(blank=True, max_length=3, null=True)),
                ('availability_status', models.CharField(max_length=20)),
                ('unit_location', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'properties',
                'managed': False,
            },
        ),
    ]
