from datetime import date, timedelta

from django.db import connections
from django.utils import timezone


QUALIFIED_STATUS_NAMES = (
    "Seguimiento activo",
    "Requerimiento definido",
    "Reunión Agendada",
    "Reunión Realizada",
    "En visitas",
    "Contrato de Corretaje Firmado",
    "En Negociación",
)


def _dict_rows(cursor):
    columns = [column[0] for column in cursor.description]
    return [dict(zip(columns, row)) for row in cursor.fetchall()]


def _one(cursor):
    rows = _dict_rows(cursor)
    return rows[0] if rows else {}


def _qualified_status_placeholders():
    return ",".join(["%s"] * len(QUALIFIED_STATUS_NAMES))


def get_management_dashboard(
    date_from: date, date_to: date, cohort_date: date | None
):
    """
    Read-only analytics over dbpropify_be.

    All writes generated by Prometeo belong to the default database. This
    service intentionally uses only SELECT statements against `propifai`.
    """
    now = timezone.now()
    qualified_placeholders = _qualified_status_placeholders()
    qualified_params = list(QUALIFIED_STATUS_NAMES)

    with connections["propifai"].cursor() as cursor:
        cursor.execute(
            """
            WITH last_activity AS (
                SELECT lead_id, MAX(created_at) AS last_activity_at
                FROM dbo.lead_activity
                GROUP BY lead_id
            )
            SELECT
                COUNT_BIG(*) AS total_leads,
                SUM(CASE WHEN l.assigned_to_id IS NULL THEN 1 ELSE 0 END) AS unassigned,
                SUM(CASE WHEN l.unread_count > 0 THEN 1 ELSE 0 END) AS unread,
                SUM(CASE
                    WHEN COALESCE(a.last_activity_at, l.created_at) < DATEADD(day, -7, SYSDATETIMEOFFSET())
                     AND LOWER(ls.name) NOT IN ('no interesado', 'cerrado', 'vendido')
                    THEN 1 ELSE 0 END) AS stalled,
                COUNT_BIG(*) AS new_in_period
            FROM dbo.lead l
            LEFT JOIN dbo.lead_status ls ON ls.id = l.lead_status_id
            LEFT JOIN last_activity a ON a.lead_id = l.id
            WHERE CAST(
                SWITCHOFFSET(COALESCE(l.date_entry, l.created_at), '-05:00')
                AS date
            ) BETWEEN %s AND %s
            """,
            [date_from, date_to],
        )
        overview = _one(cursor)

        cursor.execute(
            """
            SELECT
                SUM(CASE WHEN e.start_time >= SYSDATETIMEOFFSET()
                          AND e.completed = 0
                          AND e.status IN ('pending', 'accepted')
                         THEN 1 ELSE 0 END) AS upcoming_events,
                SUM(CASE WHEN et.name = 'Visita'
                          AND e.start_time >= SYSDATETIMEOFFSET()
                          AND e.completed = 0
                          AND e.status IN ('pending', 'accepted')
                         THEN 1 ELSE 0 END) AS upcoming_visits,
                SUM(CASE WHEN e.start_time < SYSDATETIMEOFFSET()
                          AND e.completed = 0
                          AND e.status IN ('pending', 'accepted')
                         THEN 1 ELSE 0 END) AS overdue_events
            FROM dbo.[event] e
            LEFT JOIN dbo.event_type et ON et.id = e.event_type_id
            INNER JOIN dbo.lead l ON l.id = e.lead_id
            WHERE CAST(
                SWITCHOFFSET(COALESCE(l.date_entry, l.created_at), '-05:00')
                AS date
            ) BETWEEN %s AND %s
            """,
            [date_from, date_to],
        )
        overview.update(_one(cursor))

        funnel_date_clause = (
            """CAST(
                SWITCHOFFSET(COALESCE(l.date_entry, l.created_at), '-05:00')
                AS date
            ) = %s"""
            if cohort_date
            else """CAST(
                SWITCHOFFSET(COALESCE(l.date_entry, l.created_at), '-05:00')
                AS date
            ) BETWEEN %s AND %s"""
        )
        funnel_date_params = (
            [cohort_date] if cohort_date else [date_from, date_to]
        )
        cursor.execute(
            f"""
            WITH base AS (
                SELECT
                    l.id,
                    CAST(SWITCHOFFSET(COALESCE(l.date_entry, l.created_at), '-05:00') AS date) AS cohort_date
                FROM dbo.lead l
                WHERE CAST(
                    SWITCHOFFSET(COALESCE(l.date_entry, l.created_at), '-05:00')
                    AS date
                ) BETWEEN %s AND %s
            ),
            contacted AS (
                SELECT h.lead_id, MIN(h.created_at) AS reached_at
                FROM dbo.lead_status_history h
                JOIN dbo.lead_status s ON s.id = h.to_status_id
                WHERE LOWER(s.name) <> 'nuevo'
                GROUP BY h.lead_id
            ),
            qualified AS (
                SELECT h.lead_id, MIN(h.created_at) AS reached_at
                FROM dbo.lead_status_history h
                JOIN dbo.lead_status s ON s.id = h.to_status_id
                WHERE s.name IN ({qualified_placeholders})
                GROUP BY h.lead_id
            ),
            visits AS (
                SELECT e.lead_id, MIN(e.created_at) AS reached_at
                FROM dbo.[event] e
                JOIN dbo.event_type et ON et.id = e.event_type_id
                WHERE et.name = 'Visita' AND e.lead_id IS NOT NULL
                GROUP BY e.lead_id
            )
            SELECT
                b.cohort_date,
                COUNT_BIG(*) AS total,
                SUM(CASE WHEN DATEDIFF(day, b.cohort_date, c.reached_at) BETWEEN 0 AND 1 THEN 1 ELSE 0 END) AS contacted_d1,
                SUM(CASE WHEN DATEDIFF(day, b.cohort_date, q.reached_at) BETWEEN 0 AND 1 THEN 1 ELSE 0 END) AS qualified_d1,
                SUM(CASE WHEN DATEDIFF(day, b.cohort_date, q.reached_at) BETWEEN 0 AND 3 THEN 1 ELSE 0 END) AS qualified_d3,
                SUM(CASE WHEN DATEDIFF(day, b.cohort_date, v.reached_at) BETWEEN 0 AND 7 THEN 1 ELSE 0 END) AS visits_d7
            FROM base b
            LEFT JOIN contacted c ON c.lead_id = b.id
            LEFT JOIN qualified q ON q.lead_id = b.id
            LEFT JOIN visits v ON v.lead_id = b.id
            GROUP BY b.cohort_date
            ORDER BY b.cohort_date DESC
            """,
            [date_from, date_to, *qualified_params],
        )
        cohorts = _dict_rows(cursor)

        cursor.execute(
            f"""
            WITH base AS (
                SELECT
                    l.id,
                    COALESCE(l.date_entry, l.created_at) AS entered_at,
                    l.date_last_message,
                    l.lead_status_id
                FROM dbo.lead l
                WHERE {funnel_date_clause}
            ),
            contacted AS (
                SELECT h.lead_id, MIN(h.created_at) AS reached_at
                FROM dbo.lead_status_history h
                JOIN dbo.lead_status s ON s.id = h.to_status_id
                WHERE LOWER(s.name) <> 'nuevo'
                GROUP BY h.lead_id
            ),
            qualified AS (
                SELECT h.lead_id, MIN(h.created_at) AS reached_at
                FROM dbo.lead_status_history h
                JOIN dbo.lead_status s ON s.id = h.to_status_id
                WHERE s.name IN ({qualified_placeholders})
                GROUP BY h.lead_id
            ),
            visits AS (
                SELECT e.lead_id, MIN(e.created_at) AS reached_at
                FROM dbo.[event] e
                JOIN dbo.event_type et ON et.id = e.event_type_id
                WHERE et.name = 'Visita' AND e.lead_id IS NOT NULL
                GROUP BY e.lead_id
            )
            SELECT
                COUNT_BIG(*) AS entered,
                SUM(CASE WHEN c.reached_at IS NOT NULL THEN 1 ELSE 0 END) AS contacted,
                SUM(CASE WHEN q.reached_at IS NOT NULL THEN 1 ELSE 0 END) AS qualified_proxy,
                SUM(CASE WHEN v.reached_at IS NOT NULL THEN 1 ELSE 0 END) AS visit_scheduled,
                SUM(CASE WHEN b.date_last_message >= DATEADD(day, -2, SYSDATETIMEOFFSET())
                          THEN 1 ELSE 0 END) AS active_last_48h
            FROM base b
            LEFT JOIN contacted c ON c.lead_id = b.id
            LEFT JOIN qualified q ON q.lead_id = b.id
            LEFT JOIN visits v ON v.lead_id = b.id
            """,
            [*funnel_date_params, *qualified_params],
        )
        selected_cohort = _one(cursor)

        cursor.execute(
            """
            WITH last_activity AS (
                SELECT lead_id, MAX(created_at) AS last_activity_at
                FROM dbo.lead_activity
                GROUP BY lead_id
            )
            SELECT TOP 8
                l.assigned_to_id AS agent_id,
                COALESCE(NULLIF(LTRIM(RTRIM(CONCAT(u.first_name, ' ', u.last_name))), ''), u.username, 'Sin asignar') AS agent_name,
                COUNT_BIG(*) AS leads,
                SUM(CASE WHEN l.unread_count > 0 THEN 1 ELSE 0 END) AS unread,
                SUM(CASE WHEN COALESCE(a.last_activity_at, l.created_at) < DATEADD(day, -7, SYSDATETIMEOFFSET())
                         THEN 1 ELSE 0 END) AS stalled
            FROM dbo.lead l
            LEFT JOIN dbo.[user] u ON u.id = l.assigned_to_id
            LEFT JOIN last_activity a ON a.lead_id = l.id
            WHERE CAST(
                SWITCHOFFSET(COALESCE(l.date_entry, l.created_at), '-05:00')
                AS date
            ) BETWEEN %s AND %s
            GROUP BY l.assigned_to_id, u.first_name, u.last_name, u.username
            ORDER BY unread DESC, stalled DESC, leads DESC
            """,
            [date_from, date_to],
        )
        agent_load = _dict_rows(cursor)

        cursor.execute(
            """
            SELECT
                COUNT_BIG(*) AS total,
                SUM(CASE WHEN assigned_to_id IS NULL THEN 1 ELSE 0 END) AS no_agent,
                SUM(CASE WHEN date_last_message IS NULL THEN 1 ELSE 0 END) AS no_last_message,
                SUM(CASE WHEN id_chatwoot IS NULL THEN 1 ELSE 0 END) AS no_chatwoot,
                SUM(CASE WHEN contact_id IS NULL THEN 1 ELSE 0 END) AS no_contact
            FROM dbo.lead
            WHERE CAST(
                SWITCHOFFSET(COALESCE(date_entry, created_at), '-05:00')
                AS date
            ) BETWEEN %s AND %s
            """,
            [date_from, date_to],
        )
        data_quality = _one(cursor)

        cursor.execute(
            """
            SELECT
                SUM(CASE WHEN lead_id IS NULL THEN 1 ELSE 0 END) AS events_without_lead,
                SUM(CASE WHEN start_time < '2000-01-01' THEN 1 ELSE 0 END) AS invalid_dates,
                COUNT_BIG(*) AS total_events
            FROM dbo.[event]
            WHERE (
                lead_id IN (
                    SELECT id
                    FROM dbo.lead
                    WHERE CAST(
                        SWITCHOFFSET(COALESCE(date_entry, created_at), '-05:00')
                        AS date
                    ) BETWEEN %s AND %s
                )
                OR (
                    lead_id IS NULL
                    AND CAST(SWITCHOFFSET(created_at, '-05:00') AS date)
                        BETWEEN %s AND %s
                )
            )
            """,
            [date_from, date_to, date_from, date_to],
        )
        data_quality.update(_one(cursor))

    for row in cohorts:
        total = int(row["total"] or 0)
        for key in ("contacted_d1", "qualified_d1", "qualified_d3", "visits_d7"):
            value = int(row[key] or 0)
            row[key] = value
            row[f"{key}_pct"] = round((value / total * 100), 1) if total else 0
        row["total"] = total

    return {
        "generated_at": now,
        "date_from": date_from,
        "date_to": date_to,
        "cohort_date": cohort_date,
        "funnel_scope_from": cohort_date or date_from,
        "funnel_scope_to": cohort_date or date_to,
        "overview": overview,
        "cohorts": cohorts,
        "selected_cohort": selected_cohort,
        "agent_load": agent_load,
        "data_quality": data_quality,
        "qualification_ready": False,
    }


def normalized_period(date_from_raw, date_to_raw):
    today = timezone.localdate()
    default_from = today - timedelta(days=13)
    try:
        date_from = date.fromisoformat(date_from_raw) if date_from_raw else default_from
    except ValueError:
        date_from = default_from
    try:
        date_to = date.fromisoformat(date_to_raw) if date_to_raw else today
    except ValueError:
        date_to = today
    if date_from > date_to:
        date_from, date_to = date_to, date_from
    if (date_to - date_from).days > 90:
        date_from = date_to - timedelta(days=90)
    return date_from, date_to
