# Generated by Django 5.2.10 on 2026-02-16 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigracionPendienteRequerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campo_bd', models.CharField(max_length=100)),
                ('titulo_display', models.CharField(max_length=150)),
                ('tipo_dato', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('ejecutada_en', models.DateTimeField(blank=True, null=True)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Migración Pendiente Requerimiento',
                'verbose_name_plural': 'Migraciones Pendientes Requerimiento',
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CampoDinamicoRequerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campo_bd', models.CharField(max_length=100, unique=True)),
                ('titulo_display', models.CharField(max_length=150)),
                ('tipo_dato', models.CharField(max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campo Dinámico Requerimiento',
                'verbose_name_plural': 'Campos Dinámicos Requerimiento',
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MapeoFuenteRequerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fuente', models.CharField(max_length=100)),
                ('portal_origen', models.CharField(max_length=50)),
                ('mapeos_confirmados', models.JSONField(default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mapeo de Fuente Requerimiento',
                'verbose_name_plural': 'Mapeos de Fuentes Requerimiento',
                'unique_together': {('nombre_fuente', 'portal_origen')},
            },
        ),
        migrations.CreateModel(
            name='RequerimientoRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente_excel', models.CharField(max_length=100)),
                ('fecha_ingesta', models.DateTimeField(auto_now_add=True)),
                ('tipo_requerimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cliente_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('ubicacion_deseada', models.CharField(blank=True, max_length=255, null=True)),
                ('presupuesto_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('presupuesto_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('metros_cuadrados_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metros_cuadrados_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('habitaciones_min', models.IntegerField(blank=True, null=True)),
                ('habitaciones_max', models.IntegerField(blank=True, null=True)),
                ('banos_min', models.IntegerField(blank=True, null=True)),
                ('banos_max', models.IntegerField(blank=True, null=True)),
                ('estacionamientos_min', models.IntegerField(blank=True, null=True)),
                ('estacionamientos_max', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='Activo', max_length=50)),
                ('prioridad', models.CharField(default='Media', max_length=20)),
                ('atributos_extras', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Requerimiento Raw',
                'verbose_name_plural': 'Requerimientos Raw',
                'indexes': [models.Index(fields=['fuente_excel', 'fecha_ingesta'], name='requerimien_fuente__a6507c_idx'), models.Index(fields=['tipo_requerimiento'], name='requerimien_tipo_re_68263b_idx'), models.Index(fields=['estado'], name='requerimien_estado_450c07_idx'), models.Index(fields=['prioridad'], name='requerimien_priorid_4b0434_idx')],
            },
        ),
    ]
