# Generated by Django 5.2.10 on 2026-02-16 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='requerimientoraw',
            name='requerimien_tipo_re_68263b_idx',
        ),
        migrations.RemoveIndex(
            model_name='requerimientoraw',
            name='requerimien_estado_450c07_idx',
        ),
        migrations.RemoveIndex(
            model_name='requerimientoraw',
            name='requerimien_priorid_4b0434_idx',
        ),
        migrations.RemoveField(
            model_name='requerimientoraw',
            name='banos_max',
        ),
        migrations.RemoveField(
            model_name='requerimientoraw',
            name='banos_min',
        ),
        migrations.RemoveField(
            model_name='requerimientoraw',
            name='cliente_email',
        ),
        migrations.RemoveField(
            model_name='requerimientoraw',
            name='cliente_nombre',
        ),
        migrations.RemoveField(
            model_name='requerimientoraw',
            name='cliente_telefono',
        ),
        migrations.RemoveField(
            model_name='requerimientoraw',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='requerimientoraw',
            name='estacionamientos_max',
        ),
        migrations.RemoveField(
            model_name='requerimientoraw',
            name='estacionamientos_min',
        ),
        migrations.RemoveField(
            model_name='requerimientoraw',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='requerimientoraw',
            name='habitaciones_max',
        ),
        migrations.RemoveField(
            model_name='requerimientoraw',
            name='habitaciones_min',
        ),
        migrations.RemoveField(
            model_name='requerimientoraw',
            name='metros_cuadrados_max',
        ),
        migrations.RemoveField(
            model_name='requerimientoraw',
            name='metros_cuadrados_min',
        ),
        migrations.RemoveField(
            model_name='requerimientoraw',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='requerimientoraw',
            name='presupuesto_max',
        ),
        migrations.RemoveField(
            model_name='requerimientoraw',
            name='presupuesto_min',
        ),
        migrations.RemoveField(
            model_name='requerimientoraw',
            name='prioridad',
        ),
        migrations.RemoveField(
            model_name='requerimientoraw',
            name='tipo_requerimiento',
        ),
        migrations.RemoveField(
            model_name='requerimientoraw',
            name='ubicacion_deseada',
        ),
    ]
