# Generated by Django 5.2.10 on 2026-02-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0002_remove_requerimientoraw_requerimien_tipo_re_68263b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(choices=[('exito_inmobiliario', 'Whatsapp Éxito Inmobiliario'), ('inmobiliarias_unidas', 'Whatsapp Inmobiliarias Unidas'), ('otro', 'Otro')], db_index=True, default='otro', help_text='Grupo de WhatsApp de donde proviene el mensaje', max_length=60, verbose_name='Grupo WhatsApp')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha del mensaje')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora del mensaje')),
                ('agente', models.CharField(blank=True, db_index=True, help_text='Nombre del agente inmobiliario que publicó el mensaje', max_length=120, verbose_name='Agente')),
                ('tipo_original', models.CharField(blank=True, help_text='Valor tal como venía en la columna "tipo" del Excel exportado', max_length=80, verbose_name='Tipo original')),
                ('condicion', models.CharField(choices=[('compra', 'Compra'), ('alquiler', 'Alquiler'), ('ambos', 'Compra y Alquiler'), ('no_especificado', 'No Especificado')], db_index=True, default='no_especificado', help_text='¿El cliente busca comprar o alquilar?', max_length=20, verbose_name='Condición')),
                ('tipo_propiedad', models.CharField(choices=[('departamento', 'Departamento'), ('casa', 'Casa'), ('terreno', 'Terreno'), ('oficina', 'Oficina'), ('local_comercial', 'Local Comercial'), ('almacen', 'Almacén'), ('no_especificado', 'No Especificado')], db_index=True, default='no_especificado', max_length=20, verbose_name='Tipo de propiedad')),
                ('distritos', models.CharField(blank=True, help_text='Uno o varios distritos separados por coma. Ej: Cayma, Yanahuara', max_length=300, verbose_name='Distritos')),
                ('presupuesto_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Presupuesto (monto)')),
                ('presupuesto_moneda', models.CharField(choices=[('USD', 'Dólares (USD)'), ('PEN', 'Soles (PEN)'), ('no_especificado', 'No Especificado')], default='no_especificado', max_length=20, verbose_name='Moneda')),
                ('presupuesto_forma_pago', models.CharField(choices=[('contado', 'Al Contado'), ('financiado', 'Financiado / Crédito'), ('no_especificado', 'No Especificado')], default='no_especificado', max_length=20, verbose_name='Forma de pago')),
                ('habitaciones', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='N° habitaciones')),
                ('banos', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='N° baños')),
                ('cochera', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('indiferente', 'Indiferente')], default='indiferente', max_length=12, verbose_name='Cochera')),
                ('ascensor', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('indiferente', 'Indiferente')], default='indiferente', max_length=12, verbose_name='Ascensor')),
                ('amueblado', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('indiferente', 'Indiferente')], default='indiferente', max_length=12, verbose_name='Amueblado')),
                ('area_m2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Área (m²)')),
                ('piso_preferencia', models.CharField(blank=True, help_text='Ej: "primer piso", "a partir de piso 3", "piso 5"', max_length=60, verbose_name='Preferencia de piso')),
                ('caracteristicas_extra', models.CharField(blank=True, help_text='Lista separada por coma. Ej: balcón, jardín, URGENTE, seguridad', max_length=300, verbose_name='Características extra')),
                ('agente_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del agente')),
                ('requerimiento', models.TextField(help_text='Mensaje completo tal como fue publicado en el grupo de WhatsApp', verbose_name='Requerimiento (texto original)')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
                'db_table': 'requerimiento',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.RemoveField(
            model_name='campodinamicorequerimiento',
            name='creado_por',
        ),
        migrations.DeleteModel(
            name='MapeoFuenteRequerimiento',
        ),
        migrations.DeleteModel(
            name='MigracionPendienteRequerimiento',
        ),
        migrations.DeleteModel(
            name='RequerimientoRaw',
        ),
        migrations.AddIndex(
            model_name='requerimiento',
            index=models.Index(fields=['condicion', 'tipo_propiedad'], name='idx_cond_tipo'),
        ),
        migrations.AddIndex(
            model_name='requerimiento',
            index=models.Index(fields=['fecha'], name='idx_fecha'),
        ),
        migrations.AddIndex(
            model_name='requerimiento',
            index=models.Index(fields=['presupuesto_moneda', 'presupuesto_monto'], name='idx_presupuesto'),
        ),
        migrations.DeleteModel(
            name='CampoDinamicoRequerimiento',
        ),
    ]
