# Generated by Django 5.2.10 on 2026-02-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0003_requerimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='fuente',
            field=models.CharField(choices=[('exito_inmobiliario', 'Whatsapp Éxito Inmobiliario'), ('inmobiliarias_unidas', 'Whatsapp Inmobiliarias Unidas'), ('red_inmobiliaria', 'WhatsApp Red Inmobiliaria Arequipa'), ('otro', 'Otro')], db_index=True, default='otro', help_text='Grupo de WhatsApp de donde proviene el mensaje', max_length=60, verbose_name='Grupo WhatsApp'),
        ),
    ]
