# Generated by Django 5.2.10 on 2026-05-14 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmobiliaria',
            name='icono_marcador',
            field=models.ImageField(blank=True, help_text='Ícono PNG para el marcador en el mapa (recomendado: 40×40 px, fondo transparente)', null=True, upload_to='iconos_marcadores/', validators=[django.core.validators.FileExtensionValidator(['png'])], verbose_name='Ícono de marcador'),
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la inmobiliaria (PNG recomendado, máx. 200×200 px)', null=True, upload_to='logos_inmobiliarias/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Logo'),
        ),
    ]
