# Generated by Django 5.2.10 on 2026-05-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0003_agente_codigo_agente_agente_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='correo_electronico',
            field=models.EmailField(blank=True, help_text='Dirección de correo electrónico del agente', max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='telefono',
            field=models.CharField(help_text='Número de contacto del agente (formato E.164: +51999888777)', max_length=20, verbose_name='Teléfono'),
        ),
    ]
