# Generated by Django 5.0.6 on 2026-01-30 23:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuenteWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True, validators=[django.core.validators.URLValidator()], verbose_name='URL completa')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre descriptivo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('estatica', 'Estática'), ('dinamica', 'Dinámica')], default='estatica', max_length=10, verbose_name='Tipo de fuente')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('eliminada', 'Eliminada')], default='activa', max_length=10, verbose_name='Estado')),
                ('prioridad', models.IntegerField(choices=[(1, 'Muy baja'), (2, 'Baja'), (3, 'Media'), (4, 'Alta'), (5, 'Muy alta')], default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Prioridad (1-5)')),
                ('frecuencia_revision_horas', models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='Frecuencia de revisión (horas)')),
                ('user_agent_personalizado', models.CharField(blank=True, max_length=200, verbose_name='User-Agent personalizado')),
                ('respetar_robots_txt', models.BooleanField(default=True, verbose_name='Respetar robots.txt')),
                ('delay_entre_requests', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Delay entre requests (segundos)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_ultima_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha última revisión')),
                ('fecha_proxima_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha próxima revisión')),
                ('total_capturas', models.IntegerField(default=0, verbose_name='Total de capturas')),
                ('total_cambios_detectados', models.IntegerField(default=0, verbose_name='Total de cambios detectados')),
                ('tasa_cambio_porcentaje', models.FloatField(default=0.0, verbose_name='Tasa de cambio (%)')),
                ('profundidad_descubrimiento', models.IntegerField(default=0, verbose_name='Profundidad de descubrimiento')),
                ('descubierta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuentes_descubiertas', to='semillas.fuenteweb', verbose_name='Descubierta por')),
            ],
            options={
                'verbose_name': 'Fuente Web',
                'verbose_name_plural': 'Fuentes Web',
                'ordering': ['-prioridad', 'fecha_proxima_revision'],
                'indexes': [models.Index(fields=['estado', 'fecha_proxima_revision'], name='semillas_fu_estado_721f01_idx'), models.Index(fields=['tipo', 'prioridad'], name='semillas_fu_tipo_488fbb_idx')],
            },
        ),
    ]
