# Generated by Django 5.2.10 on 2026-05-14 17:08

import agentes.storage_backends
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0002_logo_icono_marcador'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='codigo_agente',
            field=models.CharField(blank=True, help_text='Código interno o ID del agente (ej: AG-001)', max_length=20, verbose_name='Código de agente'),
        ),
        migrations.AddField(
            model_name='agente',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='URL del perfil o página de Facebook', max_length=500, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='agente',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='URL del perfil de Instagram', max_length=500, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='agente',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='URL del perfil de LinkedIn', max_length=500, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='agente',
            name='sitio_web',
            field=models.URLField(blank=True, help_text='URL de la página web personal o profesional', max_length=500, verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='inmobiliaria',
            name='icono_marcador',
            field=models.ImageField(blank=True, help_text='Ícono PNG para el marcador en el mapa (recomendado: 40×40 px, fondo transparente)', null=True, storage=agentes.storage_backends.IconoMarcadorStorage(), upload_to='iconos_marcadores/', validators=[django.core.validators.FileExtensionValidator(['png'])], verbose_name='Ícono de marcador'),
        ),
        migrations.AlterField(
            model_name='inmobiliaria',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la inmobiliaria (PNG recomendado, máx. 200×200 px, fondo claro)', null=True, storage=agentes.storage_backends.LogoStorage(), upload_to='logos_inmobiliarias/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Logo'),
        ),
    ]
