# Generated by Django 5.2.10 on 2026-05-14 17:39

import agentes.storage_backends
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0004_agente_correo_electronico_alter_agente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto del agente (JPG/PNG recomendado, máx. 400×400 px)', null=True, storage=agentes.storage_backends.FotoPerfilStorage(), upload_to='fotos_agentes/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='agente',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='URL del perfil de TikTok', max_length=500, verbose_name='TikTok'),
        ),
    ]
