"""
Django settings for webapp project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""


from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent
env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-g76()bgf_)1ygr$!a1s-iv+js-^wz_ewsc-^bu@9n24v881szs')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Allow all hosts for now, but you should restrict this in production
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'granextractorservice-emehaffsf8e2c7eg.brazilsouth-01.azurewebsites.net,acm.propifai.com,localhost,127.0.0.1').split(',')

# CSRF trusted origins for production (prevents 403 errors on POST requests)
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://acm.propifai.com,https://granextractorservice-emehaffsf8e2c7eg.brazilsouth-01.azurewebsites.net').split(',')

# Base URL for generating absolute links (e.g., for WhatsApp sharing, PDF links)
# In production, set this to: https://acm.propifai.com
BASE_URL = os.environ.get('BASE_URL', 'http://127.0.0.1:8000')

# CORS configuration
CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173'
).split(',')
CORS_ALLOW_CREDENTIALS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    # Third-party apps
    'corsheaders',
    'rest_framework',
    'django_celery_beat',
    'django_celery_results',
    
    # Project apps
    'semillas',
    'captura',
    'colas',
    'api',
    'ingestas',
    'requerimientos',
    'cuadrantizacion',
    'propifai',
    'matching',
    'acm',
    'market_analysis',
    'analisis_crm',
    'eventos',
    'intelligence',
    'meta_ads',  # Habilitado para desarrollo - dashboard de Meta Ads
    'prospects',  # Captura de prospectos inmobiliarios desde el celular
    'whatsapp_extractor',  # Extracción automática de requerimientos desde WhatsApp
    'agentes',  # Gestión de agentes e inmobiliarias
    'canvas',   # PropFlow Visual Canvas — lienzos interactivos
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # Nuestro middleware ANTES que el de Django auth para limpiar
    # sesiones con IDs inválidos (ej: enteros pre-UUID) antes de
    # que Django intente resolver request.user y falle.
    'intelligence.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'

# Custom user model
AUTH_USER_MODEL = 'intelligence.User'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT', default='1433'),
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
        },
    },
    'propifai': {
        'ENGINE': 'mssql',
        'NAME': env('PROPIFAI_DB_NAME', default='dbpropify_be'),
        'USER': env('PROPIFAI_DB_USER', default='sqladmin'),
        'PASSWORD': env('PROPIFAI_DB_PASS', default='Propify12345@'),
        'HOST': env('PROPIFAI_DB_HOST', default='janis-server.database.windows.net'),
        'PORT': env('PROPIFAI_DB_PORT', default='1433'),
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
        },
    }
}

# Database routers for multiple databases
DATABASE_ROUTERS = ['routers.PropifaiRouter', 'routers.DefaultRouter']

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-pe'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# WhiteNoise configuration for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files (user uploads) — using Azure Blob Storage for prospects
DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'

# Azure Storage Configuration for Media Files (Prospects Photos)
AZURE_ACCOUNT_NAME = env('AZURE_STORAGE_ACCOUNT_NAME', default='granextractormedia')
AZURE_ACCOUNT_KEY = env('AZURE_STORAGE_ACCOUNT_KEY', default='')
AZURE_CONTAINER = env('AZURE_PHOTOS_CONTAINER', default='fotosprospecciones')
AZURE_CUSTOM_DOMAIN = f'{AZURE_ACCOUNT_NAME}.blob.core.windows.net'
MEDIA_URL = f'https://{AZURE_CUSTOM_DOMAIN}/{AZURE_CONTAINER}/'
MEDIA_ROOT = None  # Not needed when using Azure Storage

# Azure Storage Configuration for Logos and Marker Icons (Agentes app)
AZURE_LOGOS_CONTAINER = env('AZURE_LOGOS_CONTAINER', default='logos')
AZURE_ICONOS_CONTAINER = env('AZURE_ICONOS_CONTAINER', default='iconosmarcadores')
AZURE_FOTOS_AGENTES_CONTAINER = env('AZURE_FOTOS_AGENTES_CONTAINER', default='fotosperfiles')

# Canvas / Lienzo — Contenedor para archivos subidos al canvas
LIENZO_STORAGE_CONTAINER = env('LIENZO_STORAGE_CONTAINER', default='lienzostorage')

# Security settings for production
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# For HTTPS in production (uncomment when you have SSL)
# SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Proxy configuration for Azure App Service (terminates SSL at proxy level)
# This tells Django to trust the X-Forwarded-Proto header from Azure's proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'memory://')
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Aprendizaje operativo PIL: solo telemetría, nunca mutación automática.
LEARNING_TELEMETRY_ENABLED = env.bool('LEARNING_TELEMETRY_ENABLED', default=True)
LEARNING_AI_AUDIT_ALL = env.bool('LEARNING_AI_AUDIT_ALL', default=True)
LEARNING_ALLOW_CONFIG_MUTATION = env.bool(
    'LEARNING_ALLOW_CONFIG_MUTATION', default=False
)

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Web scraping configuration
SCRAPING_USER_AGENT = 'ElGranExtractor/1.0 (+https://granextractor.azurewebsites.net)'
SCRAPING_DEFAULT_DELAY = 3  # seconds between requests
SCRAPING_MAX_RETRIES = 3
SCRAPING_TIMEOUT = 30  # seconds

# Storage for raw HTML (using database for simplicity, can be changed to Azure Blob Storage later)
RAW_HTML_STORAGE = 'blob_storage'  # 'database' or 'blob_storage'

# Azure Blob Storage Configuration (for raw documents)
AZURE_STORAGE_CONNECTION_STRING = env('AZURE_STORAGE_CONNECTION_STRING', default='')
# django-storages AzureStorage busca settings.AZURE_CONNECTION_STRING
AZURE_CONNECTION_STRING = AZURE_STORAGE_CONNECTION_STRING
AZURE_STORAGE_CONTAINER_NAME = env('AZURE_STORAGE_CONTAINER_NAME', default='documentoscrudos')
AZURE_STORAGE_ACCOUNT_NAME = env('AZURE_STORAGE_ACCOUNT_NAME', default='granextractormedia')
AZURE_STORAGE_ACCOUNT_KEY = env('AZURE_STORAGE_ACCOUNT_KEY', default='')

# External API Configuration for Property Integration
API_EXTERNA_URL = env('API_EXTERNA_URL', default='http://localhost/dashboard/api/properties/with-docs/')
API_EXTERNA_KEY = env('API_EXTERNA_KEY', default='ItBJSnE6F7gIG5uhnPh0mtXmQ9yjE8ZgqtIjTU')
API_EXTERNA_TIMEOUT = env.int('API_EXTERNA_TIMEOUT', default=10)

# Qwen3-VL API Key for AI processing of prospect images
QWEN_API_KEY = env('QWEN_API_KEY', default='')

# Monkey patch para corregir el error 'super' object has no attribute 'dicts'
# en Django 5.0.6 con Python 3.14.2
import django.template.context

def patched_context_copy(self):
    """Versión segura de __copy__ para Context que evita llamar a super().__copy__()."""
    # Crear nueva instancia
    duplicate = self.__class__.__new__(self.__class__)
    
    # Copiar todos los atributos existentes
    duplicate.__dict__.update(self.__dict__)
    
    # Asegurar que dicts sea una copia
    duplicate.dicts = self.dicts[:] if hasattr(self, 'dicts') and self.dicts else []
    
    return duplicate

# Aplicar patch a Context.__copy__
django.template.context.Context.__copy__ = patched_context_copy

# También necesitamos parchear BaseContext.__copy__ porque Context llama a super().__copy__()
def patched_basecontext_copy(self):
    """Versión segura de __copy__ para BaseContext."""
    duplicate = self.__class__.__new__(self.__class__)
    duplicate.__dict__.update(self.__dict__)
    duplicate.dicts = self.dicts[:] if hasattr(self, 'dicts') and self.dicts else []
    return duplicate

django.template.context.BaseContext.__copy__ = patched_basecontext_copy

print("Monkey patch aplicado a django.template.context.__copy__")

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {module}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': 'DEBUG',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
            'level': 'INFO',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'intelligence': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'intelligence.views': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
